(() => {
const offers=[...(window.CATALOGUE||[]),...(typeof CATALOGUE_1!=='undefined'?CATALOGUE_1:[]),...(typeof CATALOGUE_2!=='undefined'?CATALOGUE_2:[]),...(typeof CATALOGUE_3!=='undefined'?CATALOGUE_3:[]),...(typeof CATALOGUE_4!=='undefined'?CATALOGUE_4:[]),...(typeof CATALOGUE_5!=='undefined'?CATALOGUE_5:[])];
const uniq=new Map();offers.forEach(o=>o&&o.id&&uniq.set(o.id,o));const catalogue=[...uniq.values()];
const defs=[
 {name:'Business Advisory',short:'BA',color:'#DAFF00',rgb:'218,255,0',caps:[['Strategy & Roadmaps',['roadmap']],['Governance & Operating Model',['maturity','finops']],['Change & Adoption',['copilot-deploy','managed']]]},
 {name:'Data & AI',short:'AI',color:'#9B9BFF',rgb:'155,155,255',caps:[['AI & Copilot',['ai-envision','copilot-readiness','copilot-deploy','sovereign-ai']],['Data Platforms',['data-modern']],['Automation',['powerplatform']]]},
 {name:'Security',short:'SEC',color:'#FF00FF',rgb:'255,0,255',caps:[['Cyber Strategy',['maturity','cyber-recovery']],['Security Operations',['managed-sec']],['Secure Access',['sase']],['AI Security',['sovereign-ai']]]},
 {name:'Hybrid Cloud',short:'HC',color:'#00FFFF',rgb:'0,255,255',caps:[['Azure & Cloud',['azure-modern','finops']],['Resilience',['cyber-recovery']],['Virtual Platforms',['avd']],['AI Infrastructure',['sovereign-ai']]]},
 {name:'Networking',short:'NET',color:'#00AEFF',rgb:'0,174,255',caps:[['Branch & WAN',['sdwan']],['Secure Access',['sase']],['Campus & Sites',['digital-campus','mining-resilience']],['Collaboration Network',['rooms']]]},
 {name:'Modern Work',short:'MW',color:'#78DCFF',rgb:'120,220,255',caps:[['Collaboration',['rooms','copilot-deploy']],['Endpoint',['endpoint','avd']],['Copilot Experience',['copilot-readiness','copilot-deploy']],['Industry Experience',['clinical-collab','digital-campus']]]},
 {name:'Apps & Automation',short:'APP',color:'#00FF88',rgb:'0,255,136',caps:[['Service Platforms',['servicenow']],['Low-code Automation',['powerplatform']],['Workflow Experience',['managed']]]},
 {name:'Lifecycle Services',short:'LIFE',color:'#FFB74A',rgb:'255,183,74',caps:[['Managed Operations',['managed','managed-sec']],['Optimise',['finops']],['Operate & Improve',['endpoint','sdwan','azure-modern']]]}
];
const fallback={
 'ai-envision':{id:'ai-envision',title:'AI Envisioning Workshop',tldr:'Align leaders on valuable AI use cases, constraints and a sensible first move.',timing:'Half day + readout',practices:['Data & AI'],lifecycle:['Learn','Consult']},
 'copilot-readiness':{id:'copilot-readiness',title:'Microsoft 365 Copilot Readiness',tldr:'Assess identity, information, licensing and adoption readiness before rollout.',timing:'2–4 weeks',practices:['Data & AI','Modern Work'],lifecycle:['Learn','Consult']},
 'maturity':{id:'maturity',title:'Cyber Maturity & Essential Eight',tldr:'Baseline maturity, expose material gaps and sequence an improvement roadmap.',timing:'3–5 weeks',practices:['Security','Business Advisory'],lifecycle:['Learn','Consult']}
};
const byId=new Map(catalogue.map(o=>[o.id,o]));Object.values(fallback).forEach(o=>{if(!byId.has(o.id))byId.set(o.id,o)});
const state={open:new Set(),openCaps:new Map(),selected:null};const map=document.getElementById('bubbleMap');
function capOffers(ids){return ids.map(id=>byId.get(id)).filter(Boolean)}
function weight(def){if(!state.open.has(def.name))return 1;const capSet=state.openCaps.get(def.name)||new Set();return capSet.size?7+capSet.size*2.4:4.6}
function capWeight(def,cap){const set=state.openCaps.get(def.name)||new Set();return set.has(cap[0])?4.2:1}
function render(){map.innerHTML='';defs.forEach(def=>{const open=state.open.has(def.name);const wrap=document.createElement('section');wrap.className=`practiceBubble ${open?'open':'closed'}`;wrap.style.cssText=`--accent:${def.color};--rgb:${def.rgb};--weight:${weight(def)}`;wrap.dataset.practice=def.name;
 const head=document.createElement('button');head.type='button';head.className='practiceHead';head.innerHTML=`<span class="orb">${def.short}</span><span><b>${def.name}</b><small>${open?'Click to collapse':'Open practice'}</small></span>`;head.onclick=()=>togglePractice(def.name);wrap.appendChild(head);
 const area=document.createElement('div');area.className='capabilityArea';def.caps.forEach(cap=>{const capSet=state.openCaps.get(def.name)||new Set();const capOpen=capSet.has(cap[0]);const cb=document.createElement('article');cb.className=`capBubble ${capOpen?'is-open':''}`;cb.style.setProperty('--capWeight',capWeight(def,cap));const os=capOffers(cap[1]);cb.innerHTML=`<button class="capHead" type="button"><span>Capability</span><b>${cap[0]}</b><small>${os.length} mapped offering${os.length===1?'':'s'}</small></button><div class="offerArea">${os.map(o=>`<button class="offerBubble ${state.selected===o.id?'active':''}" type="button" data-offer="${o.id}"><b>${o.title}</b><span>${o.timing||o.type||'Offering'}</span></button>`).join('')}</div>`;cb.querySelector('.capHead').onclick=()=>toggleCap(def.name,cap[0]);cb.querySelectorAll('[data-offer]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectOffer(b.dataset.offer,def,cap[0],b)});area.appendChild(cb)});wrap.appendChild(area);map.appendChild(wrap)});updateStatus()}
function togglePractice(name){if(state.open.has(name)){state.open.delete(name);state.openCaps.delete(name)}else{state.open.add(name)}state.selected=null;render()}
function toggleCap(practice,cap){state.open.add(practice);if(!state.openCaps.has(practice))state.openCaps.set(practice,new Set());const set=state.openCaps.get(practice);set.has(cap)?set.delete(cap):set.add(cap);state.selected=null;render()}
function selectOffer(id,def,cap,button){state.selected=id;const o=byId.get(id);document.getElementById('detailKicker').textContent='Offering';document.getElementById('detailTitle').textContent=o.title;document.getElementById('detailBody').textContent=o.tldr||o.summary||'Mapped offering in this portfolio pathway.';document.getElementById('trail').innerHTML=`<span>Portfolio</span><span>${def.name}</span><span>${cap}</span><span>${o.title}</span>`;document.querySelectorAll('.offerBubble').forEach(x=>x.classList.toggle('active',x.dataset.offer===id));const rect=button.getBoundingClientRect(),m=map.getBoundingClientRect();document.querySelector('.offerPopover')?.remove();const pop=document.createElement('div');pop.className='offerPopover';pop.style.cssText=`--accent:${def.color};left:${Math.max(12,Math.min(rect.left-m.left,m.width-305))}px;top:${Math.max(70,Math.min(rect.bottom-m.top+6,m.height-170))}px`;pop.innerHTML=`<div class="eyebrow">${def.name} · ${cap}</div><h3>${o.title}</h3><p>${o.tldr||o.summary||''}</p><div class="meta">${o.timing||o.type||'Offering'} · ${(o.lifecycle||[]).join(' → ')}</div>`;map.appendChild(pop)}
function updateStatus(){const opens=[...state.open];document.getElementById('portfolioSummary').textContent=`${defs.length} practices · ${opens.length} open`;document.getElementById('mapStatus').textContent=opens.length?`${opens.length} practice${opens.length===1?'':'s'} open`:'Portfolio overview';document.getElementById('mapHint').textContent=opens.length?'Open capabilities to reveal offerings; open another practice to compare.':'Open a practice to reveal its capabilities.';if(!state.selected){document.getElementById('detailKicker').textContent=opens.length?'Open branches':'How to explore';document.getElementById('detailTitle').textContent=opens.length?opens.join(' + '):'Start with any practice bubble.';document.getElementById('detailBody').textContent=opens.length?'Open one or more capabilities. A deeper branch receives more space while every other practice remains visible.':'Opening a practice increases its share of the map and reveals capabilities. Opening a capability grows that branch again and reveals the offerings customers can buy.';document.getElementById('trail').innerHTML=opens.map(n=>`<span>Portfolio → ${n}</span>`).join('')}}
document.getElementById('collapseAll').onclick=()=>{state.open.clear();state.openCaps.clear();state.selected=null;render()};document.getElementById('openAI').onclick=()=>{state.open.add('Data & AI');render()};document.getElementById('openSecurity').onclick=()=>{state.open.add('Security');render()};render();
})();