(() => {
const mobile=()=>matchMedia('(max-width:620px)').matches;const map=document.getElementById('bubbleMap');if(!map)return;
const practicePos=[[17,20],[48,14],[79,23],[26,43],[69,43],[14,68],[48,70],[82,68]];
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
function distribute(){if(!mobile())return;const practices=[...map.querySelectorAll(':scope > .practiceBubble')];const open=practices.filter(p=>p.classList.contains('open'));const closed=practices.filter(p=>p.classList.contains('closed'));
 practices.forEach((p,i)=>{const isOpen=p.classList.contains('open');let x,y,size;if(!open.length){[x,y]=practicePos[i%practicePos.length];size=92+(i%3)*5}else if(isOpen){const oi=open.indexOf(p),n=open.length;if(n===1){x=50;y=46;size=310}else if(n===2){x=oi?68:32;y=45;size=235}else{x=18+(oi%(Math.min(n,3)))*32;y=34+Math.floor(oi/3)*35;size=190}}else{const ci=closed.indexOf(p),n=closed.length;const cols=Math.min(4,n);x=12+(ci%cols)*(76/Math.max(1,cols-1));y=open.length<=2?84:88;size=66}
 p.style.setProperty('--mobile-x',x+'%');p.style.setProperty('--mobile-y',y+'%');p.style.setProperty('--mobile-size',size+'px');p.style.setProperty('--float-duration',(6+(hash(p.dataset.practice)%30)/10)+'s');p.style.setProperty('--float-delay',-((hash(p.dataset.practice)%25)/10)+'s');layoutCaps(p,size)});}
function layoutCaps(p,size){if(!p.classList.contains('open'))return;const caps=[...p.querySelectorAll('.capBubble')],opened=caps.filter(c=>c.classList.contains('is-open'));caps.forEach((c,i)=>{const isOpen=c.classList.contains('is-open');let x,y,s;if(opened.length&&isOpen){const oi=opened.indexOf(c);x=opened.length===1?50:35+oi*(30/Math.max(1,opened.length-1));y=56;s=Math.min(size*.58,175)}else{const angle=(-140+(i*(280/Math.max(1,caps.length-1))))*Math.PI/180;const radius=isOpen?0:Math.min(size*.3,88);x=50+Math.cos(angle)*radius/size*100;y=55+Math.sin(angle)*radius/size*100;s=Math.max(55,Math.min(78,size*.24))}c.style.setProperty('--cap-x',x+'%');c.style.setProperty('--cap-y',y+'%');c.style.setProperty('--cap-size',s+'px');layoutOffers(c,s)})}
function layoutOffers(c,size){if(!c.classList.contains('is-open'))return;const os=[...c.querySelectorAll('.offerBubble')];os.forEach((o,i)=>{const a=(-90+i*(360/Math.max(1,os.length)))*Math.PI/180,r=Math.min(size*.28,42);o.style.setProperty('--offer-x',(50+Math.cos(a)*r/size*100)+'%');o.style.setProperty('--offer-y',(61+Math.sin(a)*r/size*100)+'%');o.style.setProperty('--offer-size',Math.max(48,Math.min(62,size*.32))+'px')})}
const observer=new MutationObserver(()=>requestAnimationFrame(distribute));observer.observe(map,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});addEventListener('resize',distribute);requestAnimationFrame(distribute);
})();