(() => {
const map=document.getElementById('bubbleMap');if(!map)return;
const desktopPos=[[14,24],[37,18],[62,18],[86,25],[18,67],[41,73],[66,72],[87,64]];const mobilePos=[[17,20],[48,14],[79,23],[26,43],[69,43],[14,68],[48,70],[82,68]];
function small(){return matchMedia('(max-width:620px)').matches}function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
function distribute(){const practices=[...map.querySelectorAll(':scope > .practiceBubble')];if(!practices.length)return;const open=practices.filter(p=>p.classList.contains('open')),closed=practices.filter(p=>p.classList.contains('closed')),m=small(),positions=m?mobilePos:desktopPos;
 practices.forEach((p,i)=>{const isOpen=p.classList.contains('open');let x,y,size;if(!open.length){[x,y]=positions[i%positions.length];size=m?92+(i%3)*5:116+(i%3)*7}else if(isOpen){const oi=open.indexOf(p),n=open.length;if(n===1){x=50;y=m?46:49;size=m?310:480}else if(n===2){x=oi?(m?68:70):(m?32:30);y=m?45:48;size=m?235:365}else if(n<=4){const cols=2;x=m?30+(oi%2)*40:28+(oi%2)*44;y=m?31+Math.floor(oi/2)*36:30+Math.floor(oi/2)*40;size=m?185:285}else{const cols=3;x=18+(oi%cols)*32;y=28+Math.floor(oi/cols)*(m?31:36);size=m?155:225}}else{const ci=closed.indexOf(p),n=closed.length,cols=Math.min(m?4:6,n);x=(m?12:9)+(ci%cols)*((m?76:82)/Math.max(1,cols-1));y=open.length<=2?(m?85:88):(m?91:92);size=m?64:82}
 p.style.setProperty('--field-x',x+'%');p.style.setProperty('--field-y',y+'%');p.style.setProperty('--field-size',size+'px');p.style.setProperty('--float-duration',(7+(hash(p.dataset.practice)%35)/10)+'s');p.style.setProperty('--float-delay',-((hash(p.dataset.practice)%25)/10)+'s');layoutCaps(p,size,m)});}
function layoutCaps(p,size,m){if(!p.classList.contains('open'))return;const caps=[...p.querySelectorAll('.capBubble')],opened=caps.filter(c=>c.classList.contains('is-open'));caps.forEach((c,i)=>{const isOpen=c.classList.contains('is-open');let x,y,s;if(opened.length&&isOpen){const oi=opened.indexOf(c);if(opened.length===1){x=50;y=57}else{x=30+oi*(40/Math.max(1,opened.length-1));y=57}s=Math.min(size*(m?.58:.54),m?175:245)}else{const a=(-150+i*(300/Math.max(1,caps.length-1)))*Math.PI/180,r=Math.min(size*(m?.3:.31),m?88:135);x=50+Math.cos(a)*r/size*100;y=57+Math.sin(a)*r/size*100;s=Math.max(m?55:68,Math.min(m?82:104,size*(m?.24:.22)))}c.style.setProperty('--cap-x',x+'%');c.style.setProperty('--cap-y',y+'%');c.style.setProperty('--cap-size',s+'px');layoutOffers(c,s,m)})}
function layoutOffers(c,size,m){if(!c.classList.contains('is-open'))return;const os=[...c.querySelectorAll('.offerBubble')];os.forEach((o,i)=>{const a=(-90+i*(360/Math.max(1,os.length)))*Math.PI/180,r=Math.min(size*(m?.28:.3),m?42:68);o.style.setProperty('--offer-x',(50+Math.cos(a)*r/size*100)+'%');o.style.setProperty('--offer-y',(62+Math.sin(a)*r/size*100)+'%');o.style.setProperty('--offer-size',Math.max(m?48:58,Math.min(m?64:78,size*(m?.32:.28)))+'px')})}
const observer=new MutationObserver(()=>requestAnimationFrame(distribute));observer.observe(map,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});addEventListener('resize',distribute);requestAnimationFrame(distribute);
})();