const CATALOGUE_3 = [
  {
    id: 'rooms',
    title: 'Modern Meeting Rooms & Teams Rooms',
    tldr: 'Standardise meeting spaces and collaboration experience across offices and hybrid teams.',
    summary: 'A repeatable room modernisation motion covering room archetypes, technology selection, deployment standards, support and adoption.',
    timing: '6–10 weeks',
    practices: ['Collaboration', 'Networking', 'End User Computing'],
    industries: ['Education', 'Government', 'Financial Services', 'Not-for-Profit'],
    lifecycle: ['Procure', 'Implement', 'Adopt', 'Operate'],
    audiences: ['Head of Digital Workplace', 'IT Manager', 'Operations Manager'],
    type: 'Tier 2 offer', owner: 'Collaboration', reviewed: 'Reviewed Jul 2026', proof: 'Experience-led',
    triggers: ['Rooms deliver inconsistent experiences.', 'Hybrid meetings frustrate users.', 'Standards differ by site.'],
    outputs: ['Room archetypes', 'Deployment standard', 'Support model'],
    actions: ['View room archetypes', 'Open commercial path', 'See deployment plan']
  },
  {
    id: 'sdwan',
    title: 'Secure Branch & SD-WAN',
    tldr: 'Modernise branch and remote-site connectivity while simplifying security and operations.',
    summary: 'A discovery, design and migration pathway for resilient branch connectivity, central policy, secure access and operational simplification.',
    timing: '10–18 weeks',
    practices: ['Networking', 'Security', 'Lifecycle Services'],
    industries: ['Mining', 'Energy', 'Government', 'Not-for-Profit', 'Education'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Head of Infrastructure', 'Enterprise Architect', 'Operations Manager'],
    type: 'Core offer', owner: 'Networking', reviewed: 'Reviewed Aug 2026', proof: 'Remote-site fit',
    triggers: ['Branch links are expensive or unreliable.', 'Policy differs by site.', 'Remote operations need resilience.'],
    outputs: ['Site discovery', 'Target architecture', 'Migration wave plan'],
    actions: ['Open site discovery', 'View architecture', 'Compare managed option']
  },
  {
    id: 'sase',
    title: 'SASE & Secure Access Modernisation',
    tldr: 'Converge network and security policy for distributed users, branches and cloud access.',
    summary: 'A target-state and migration motion that brings secure web, zero-trust access and network policy into a coherent operating model.',
    timing: '10–16 weeks',
    practices: ['Networking', 'Security'],
    industries: ['Financial Services', 'Government', 'Education', 'Mining'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Chief Information Security Officer', 'Head of Infrastructure', 'Enterprise Architect'],
    type: 'Tier 2 offer', owner: 'Networking + Security', reviewed: 'Reviewed Jul 2026', proof: 'Cross-practice',
    triggers: ['Remote access is fragmented.', 'VPN experience is poor.', 'Policy is split across products.'],
    outputs: ['Target state', 'Vendor decision view', 'Migration sequence'],
    actions: ['Open target state', 'Qualify opportunity', 'View migration sequence']
  },
  {
    id: 'azure-modern',
    title: 'Azure Estate Modernisation',
    tldr: 'Make workload placement, landing zone, migration sequence, cost and risk visible.',
    summary: 'An assessment and modernisation pathway that maps dependencies, confirms placement, strengthens the landing zone and sequences migration or remediation.',
    timing: '4–12 weeks',
    practices: ['Hybrid Cloud', 'Business Advisory', 'Security'],
    industries: ['Government', 'Financial Services', 'Education', 'Health & Aged Care'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Head of Infrastructure', 'Enterprise Architect', 'Chief Information Officer'],
    type: 'Core offer', owner: 'Hybrid Cloud', reviewed: 'Reviewed Aug 2026', proof: 'Cloud core',
    triggers: ['The data centre lease is ending.', 'Cloud spend lacks accountability.', 'Migration has stalled.'],
    outputs: ['Placement recommendation', 'Landing-zone backlog', 'Migration roadmap'],
    actions: ['Open assessment', 'View landing zone', 'Build migration roadmap']
  },
  {
    id: 'sovereign-ai',
    title: 'Sovereign AI Infrastructure Pathway',
    tldr: 'Explore controlled AI infrastructure where sovereignty, performance or operating model matter.',
    summary: 'A synthetic emerging-offer pathway that frames workload, sovereignty, platform, security and operating-model decisions before a customer commits to infrastructure.',
    timing: '3–6 weeks',
    practices: ['Hybrid Cloud', 'Data & AI', 'Security'],
    industries: ['Government', 'Mining', 'Financial Services', 'Energy'],
    lifecycle: ['Learn', 'Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Chief Information Officer', 'Chief Information Security Officer', 'Head of Infrastructure', 'Enterprise Architect'],
    type: 'Emerging demo offer', owner: 'Hybrid Cloud + Data & AI', reviewed: 'Synthetic demo', proof: 'Illustrative',
    triggers: ['Sovereignty is a stated obligation.', 'AI workloads need local control.', 'The operating model is unresolved.'],
    outputs: ['Placement options', 'Constraint register', 'Decision record'],
    actions: ['Open executive brief', 'Compare architectures', 'Use risk framing']
  },
  {
    id: 'finops',
    title: 'Cloud Cost & FinOps Optimisation',
    tldr: 'Make cloud spend accountable and create an operating rhythm for optimisation.',
    summary: 'A cost and operating-model engagement that identifies waste, clarifies ownership and establishes repeatable governance and optimisation practices.',
    timing: '3–6 weeks',
    practices: ['Hybrid Cloud', 'Lifecycle Services', 'Business Advisory'],
    industries: ['Financial Services', 'Government', 'Education', 'Energy'],
    lifecycle: ['Consult', 'Operate'],
    audiences: ['Chief Information Officer', 'Head of Infrastructure', 'IT Manager'],
    type: 'Tier 2 offer', owner: 'Hybrid Cloud', reviewed: 'Reviewed Jul 2026', proof: 'Operate motion',
    triggers: ['Cloud bills are rising.', 'Nobody owns optimisation.', 'Forecasts are unreliable.'],
    outputs: ['Cost baseline', 'Optimisation backlog', 'FinOps operating rhythm'],
    actions: ['Open cost story', 'Run assessment', 'View optimisation plan']
  }
];
