const CATALOGUE_4 = [
  {
    id: 'data-modern',
    title: 'Data Platform Modernisation',
    tldr: 'Create a governed data foundation that can support analytics, automation and AI.',
    summary: 'A discovery and modernisation pathway for data architecture, platform choice, governance, migration and the first high-value analytics or AI use cases.',
    timing: '8–16 weeks',
    practices: ['Data & AI', 'Hybrid Cloud', 'Security'],
    industries: ['Government', 'Mining', 'Financial Services', 'Health & Aged Care', 'Energy'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Chief Information Officer', 'Enterprise Architect', 'Head of Infrastructure'],
    type: 'Core offer', owner: 'Data & AI', reviewed: 'Reviewed Aug 2026', proof: 'Data foundation',
    triggers: ['Reporting is fragmented.', 'AI plans lack trusted data.', 'Legacy platforms constrain delivery.'],
    outputs: ['Target data architecture', 'Migration backlog', 'Governance model'],
    actions: ['Open discovery guide', 'View architecture', 'Build first-use-case plan']
  },
  {
    id: 'roadmap',
    title: 'Digital Strategy & Investment Roadmap',
    tldr: 'Align current state, target state, priorities and investment sequencing around outcomes.',
    summary: 'An executive advisory engagement that creates a shared current-state view, a target direction and a sequenced roadmap with dependencies and investment choices visible.',
    timing: '4–8 weeks',
    practices: ['Business Advisory'],
    industries: ['Government', 'Mining', 'Health & Aged Care', 'Financial Services', 'Education', 'Energy', 'Not-for-Profit'],
    lifecycle: ['Learn', 'Consult'],
    audiences: ['Chief Executive Officer', 'Chief Information Officer', 'Board / Executive Leadership Team'],
    type: 'Core advisory', owner: 'Business Advisory', reviewed: 'Reviewed Aug 2026', proof: 'Executive motion',
    triggers: ['Investment is debated project by project.', 'The target state is unclear.', 'Dependencies are causing delays.'],
    outputs: ['Digital roadmap', 'Investment sequence', 'Executive presentation'],
    actions: ['Open board deck', 'Book workshop', 'View roadmap example']
  },
  {
    id: 'managed',
    title: 'Managed Operations & Continuous Improvement',
    tldr: 'Wrap delivered technology in monitoring, support, optimisation and improvement.',
    summary: 'A lifecycle layer that connects service integration, monitoring, support, governance, optimisation and continuous improvement to the technology already delivered.',
    timing: 'Ongoing service',
    practices: ['Lifecycle Services', 'Hybrid Cloud', 'Networking', 'End User Computing', 'Collaboration'],
    industries: ['Government', 'Mining', 'Health & Aged Care', 'Financial Services', 'Education', 'Energy', 'Not-for-Profit'],
    lifecycle: ['Adopt', 'Operate'],
    audiences: ['Chief Information Officer', 'Head of Infrastructure', 'IT Manager', 'Operations Manager'],
    type: 'Lifecycle layer', owner: 'Lifecycle Services', reviewed: 'Reviewed Aug 2026', proof: 'Attach motion',
    triggers: ['Operations are reactive.', 'Multiple suppliers create gaps.', 'Optimisation stops after go-live.'],
    outputs: ['Service baseline', 'Operating model', 'Continuous improvement backlog'],
    actions: ['Open service model', 'Use attach prompts', 'View operational outcomes']
  },
  {
    id: 'mining-resilience',
    title: 'Mining Site Technology Resilience',
    tldr: 'Improve site continuity across connectivity, cyber, edge infrastructure and operations.',
    summary: 'A cross-practice site assessment and improvement pathway for remote connectivity, operational resilience, cyber exposure, edge platforms and support.',
    timing: '4–10 weeks',
    practices: ['Networking', 'Security', 'Hybrid Cloud', 'Lifecycle Services'],
    industries: ['Mining'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Chief Information Officer', 'Chief Information Security Officer', 'Head of Infrastructure', 'Operations Manager'],
    type: 'Industry play', owner: 'Mining + Networking', reviewed: 'Reviewed Jul 2026', proof: 'Industry-specific',
    triggers: ['Site outages affect production.', 'OT and IT controls are converging.', 'Remote support is inconsistent.'],
    outputs: ['Site resilience baseline', 'Reference architecture', 'Improvement wave plan'],
    actions: ['Open site brief', 'Use operations questions', 'View reference architecture']
  },
  {
    id: 'clinical-collab',
    title: 'Clinical Collaboration Modernisation',
    tldr: 'Connect secure collaboration, devices and network experience to clinical continuity.',
    summary: 'An industry-specific modernisation pathway for clinical collaboration scenarios, secure endpoint access, meeting experiences and supporting connectivity.',
    timing: '8–14 weeks',
    practices: ['Collaboration', 'End User Computing', 'Networking', 'Security'],
    industries: ['Health & Aged Care'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Adopt', 'Operate'],
    audiences: ['Chief Information Officer', 'Head of Digital Workplace', 'IT Manager', 'Operations Manager'],
    type: 'Industry play', owner: 'Health + Collaboration', reviewed: 'Reviewed Jul 2026', proof: 'Clinical scenarios',
    triggers: ['Clinical hand-offs are fragmented.', 'Shared devices create friction.', 'Continuity depends on inconsistent tools.'],
    outputs: ['Clinical scenario map', 'Target experience', 'Modernisation roadmap'],
    actions: ['Open clinical brief', 'View scenario map', 'Build roadmap']
  },
  {
    id: 'digital-campus',
    title: 'Education Digital Campus Foundation',
    tldr: 'Unify campus connectivity, endpoint experience, security and operations for learning.',
    summary: 'A synthetic education play that frames student and staff experience across campus networks, devices, identity, collaboration and support.',
    timing: '6–12 weeks',
    practices: ['Networking', 'End User Computing', 'Security', 'Collaboration'],
    industries: ['Education'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Chief Information Officer', 'Head of Infrastructure', 'IT Manager'],
    type: 'Industry play', owner: 'Education + Networking', reviewed: 'Reviewed Aug 2026', proof: 'Campus-ready',
    triggers: ['Wireless experience varies by campus.', 'Device fleets are fragmented.', 'Support peaks overwhelm the team.'],
    outputs: ['Campus baseline', 'Target foundation', 'Sequenced investment plan'],
    actions: ['Open campus brief', 'Use discovery prompts', 'View target foundation']
  }
];
