const CATALOGUE_1 = [
  {
    id: 'ai-envision',
    title: 'AI Envisioning Workshop',
    tldr: 'Align executives on valuable AI use cases, constraints and a sensible first move.',
    summary: 'A facilitated executive session that turns broad AI ambition into a short list of valuable use cases, explicit constraints and an agreed first engagement.',
    timing: 'Half day + readout',
    practices: ['Data & AI', 'Business Advisory'],
    industries: ['Government', 'Mining', 'Financial Services', 'Education', 'Energy'],
    lifecycle: ['Learn', 'Consult'],
    audiences: ['Chief Executive Officer', 'Chief Information Officer', 'Board / Executive Leadership Team'],
    type: 'Core offer', owner: 'Data & AI', reviewed: 'Reviewed Aug 2026', proof: 'Executive-ready',
    triggers: ['The board wants an AI plan.', 'Teams have ideas but no shared priority.', 'Leadership needs a low-regret first move.'],
    outputs: ['Use-case shortlist', 'Constraints and readiness view', 'Recommended first engagement'],
    actions: ['Open talk track', 'Use discovery questions', 'Build 1-page brief']
  },
  {
    id: 'copilot-ready',
    title: 'Microsoft 365 Copilot Readiness',
    tldr: 'Assess identity, information, licensing and adoption readiness before rollout.',
    summary: 'A time-boxed readiness engagement across identity, information exposure, licensing, governance and adoption so the customer knows what to fix before scaling Copilot.',
    timing: '2–3 weeks',
    practices: ['Data & AI', 'Collaboration', 'Security'],
    industries: ['Government', 'Health & Aged Care', 'Financial Services', 'Education'],
    lifecycle: ['Consult', 'Adopt'],
    audiences: ['Chief Information Officer', 'Chief Information Security Officer', 'Head of Digital Workplace'],
    type: 'Core offer', owner: 'Data & AI + Collaboration', reviewed: 'Reviewed Aug 2026', proof: 'Governed',
    triggers: ['Licences exist but adoption is low.', 'Oversharing is a concern.', 'The customer needs a defensible rollout plan.'],
    outputs: ['Readiness scorecard', 'Prioritised remediation', 'Pilot and adoption plan'],
    actions: ['Open readiness checklist', 'Qualify opportunity', 'View customer story']
  },
  {
    id: 'ai-govern',
    title: 'AI Governance & Shadow AI Review',
    tldr: 'Make AI use visible, assign ownership and prioritise controls without freezing innovation.',
    summary: 'An assessment of sanctioned and unsanctioned AI usage, the data those tools can reach, policy gaps and the controls worth applying first.',
    timing: '2–4 weeks',
    practices: ['Security', 'Data & AI', 'Collaboration'],
    industries: ['Government', 'Health & Aged Care', 'Financial Services', 'Mining'],
    lifecycle: ['Consult', 'Operate'],
    audiences: ['Chief Information Security Officer', 'Chief Information Officer', 'Board / Executive Leadership Team'],
    type: 'Strategic offer', owner: 'Security + Data & AI', reviewed: 'Reviewed Jul 2026', proof: 'Cross-practice',
    triggers: ['Staff already use unapproved AI tools.', 'Risk wants an inventory and owner.', 'The board is asking about AI controls.'],
    outputs: ['AI usage inventory', 'Governance gap report', 'Prioritised control plan'],
    actions: ['Open board narrative', 'Use risk questions', 'View control map']
  },
  {
    id: 'ai-adopt',
    title: 'AI Adoption Accelerator',
    tldr: 'Move priority roles from curiosity to repeatable, measurable AI-assisted work.',
    summary: 'A focused adoption motion that selects role-based scenarios, enables champions, establishes guardrails and measures behaviour change rather than licence activation.',
    timing: '6–10 weeks',
    practices: ['Data & AI', 'Collaboration', 'Business Advisory'],
    industries: ['Government', 'Education', 'Financial Services', 'Not-for-Profit'],
    lifecycle: ['Adopt'],
    audiences: ['Head of Digital Workplace', 'Chief Information Officer', 'Operations Manager'],
    type: 'Core offer', owner: 'Data & AI + Collaboration', reviewed: 'Reviewed Aug 2026', proof: 'Adoption-led',
    triggers: ['Pilots have stalled.', 'Leaders need measurable use.', 'Teams need role-specific scenarios.'],
    outputs: ['Scenario library', 'Champion plan', 'Adoption measurement baseline'],
    actions: ['Open adoption play', 'View scenario map', 'Build measurement plan']
  },
  {
    id: 'e8',
    title: 'Cyber Maturity & Essential Eight',
    tldr: 'Baseline cyber maturity, expose material gaps and sequence an improvement roadmap.',
    summary: 'A framework-based maturity assessment that makes control gaps, business exposure, dependencies and the most sensible improvement sequence visible.',
    timing: '3–5 weeks',
    practices: ['Security', 'Business Advisory'],
    industries: ['Government', 'Education', 'Health & Aged Care', 'Not-for-Profit', 'Mining'],
    lifecycle: ['Learn', 'Consult'],
    audiences: ['Chief Information Security Officer', 'Chief Information Officer', 'IT Manager', 'Board / Executive Leadership Team'],
    type: 'Core offer', owner: 'Security', reviewed: 'Reviewed Aug 2026', proof: 'Framework-aligned',
    triggers: ['Insurance questions are getting harder.', 'The board wants assurance.', 'A framework target has been mandated.'],
    outputs: ['Maturity report', 'Prioritised roadmap', 'Executive summary'],
    actions: ['Open maturity pitch', 'Book workshop', 'View roadmap sample']
  },
  {
    id: 'identity',
    title: 'Identity Security Modernisation',
    tldr: 'Unify identity posture, conditional access and privileged access around resilience.',
    summary: 'A modernisation pathway that connects identity risk, access policy, privileged administration and operational ownership to the customer’s resilience goals.',
    timing: '6–12 weeks',
    practices: ['Security'],
    industries: ['Financial Services', 'Government', 'Health & Aged Care', 'Education'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Chief Information Security Officer', 'Enterprise Architect', 'IT Manager'],
    type: 'Core offer', owner: 'Security', reviewed: 'Reviewed Jul 2026', proof: 'Microsoft-aligned',
    triggers: ['Legacy authentication remains.', 'Privileged access is hard to evidence.', 'Identity incidents are increasing.'],
    outputs: ['Identity target state', 'Control sequence', 'Implementation backlog'],
    actions: ['Open architecture view', 'Qualify opportunity', 'Use objection guide']
  }
];
