const CATALOGUE_2 = [
  {
    id: 'managed-sec',
    title: 'Managed Security Operations',
    tldr: 'Sustain monitoring, response and service improvement with clear accountability.',
    summary: 'An ongoing operating model for security monitoring, response, governance and continuous improvement, aligned to the customer’s existing technology and obligations.',
    timing: 'Ongoing service',
    practices: ['Security', 'Lifecycle Services'],
    industries: ['Government', 'Mining', 'Financial Services', 'Health & Aged Care', 'Education'],
    lifecycle: ['Operate'],
    audiences: ['Chief Information Security Officer', 'Chief Information Officer', 'IT Manager'],
    type: 'Core service', owner: 'Security', reviewed: 'Reviewed Aug 2026', proof: 'Operate motion',
    triggers: ['Coverage is fragmented.', 'Internal teams cannot staff 24×7.', 'Response ownership is unclear.'],
    outputs: ['Service baseline', 'Response operating model', 'Improvement backlog'],
    actions: ['Open service model', 'Use attach prompts', 'View operating outcomes']
  },
  {
    id: 'servicenow',
    title: 'ServiceNow Service Management Modernisation',
    tldr: 'Replace fragmented ticketing with a trusted service platform and accountable process owners.',
    summary: 'A design and implementation motion for priority service management processes, platform configuration, migration, adoption and operational ownership.',
    timing: '10–16 weeks',
    practices: ['Apps & Automation', 'Lifecycle Services', 'Business Advisory'],
    industries: ['Government', 'Education', 'Financial Services', 'Health & Aged Care'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Adopt', 'Operate'],
    audiences: ['Chief Information Officer', 'IT Manager', 'Operations Manager'],
    type: 'Tier 2 offer', owner: 'Apps & Automation', reviewed: 'Reviewed Jul 2026', proof: 'Platform motion',
    triggers: ['The service desk cannot keep up.', 'Reporting depends on spreadsheets.', 'Process ownership is unclear.'],
    outputs: ['Configured platform', 'Process documentation', 'Trained owners and users'],
    actions: ['Open discovery guide', 'View demo story', 'See implementation path']
  },
  {
    id: 'powerplatform',
    title: 'Power Platform Automation Sprint',
    tldr: 'Find high-value manual work and rapidly prove one governed automation.',
    summary: 'A focused sprint that prioritises automation candidates, validates governance and moves one process from idea to a working pattern the customer can extend.',
    timing: '3–5 weeks',
    practices: ['Apps & Automation', 'Data & AI'],
    industries: ['Government', 'Health & Aged Care', 'Not-for-Profit', 'Education'],
    lifecycle: ['Learn', 'Consult', 'Implement', 'Adopt'],
    audiences: ['Chief Information Officer', 'Head of Digital Workplace', 'IT Manager', 'Operations Manager'],
    type: 'Tier 2 offer', owner: 'Apps & Automation', reviewed: 'Reviewed Aug 2026', proof: 'Fast value',
    triggers: ['Teams rely on manual hand-offs.', 'A backlog of small automation ideas exists.', 'Governance is blocking progress.'],
    outputs: ['Prioritised backlog', 'Working automation', 'Governance pattern'],
    actions: ['Open use-case guide', 'Book sprint', 'View governance model']
  },
  {
    id: 'endpoint',
    title: 'Modern Endpoint Management',
    tldr: 'Standardise device lifecycle, security and management while improving employee experience.',
    summary: 'A modern endpoint pathway spanning device strategy, enrolment, policy, security posture, application delivery and the full operational lifecycle.',
    timing: '8–14 weeks',
    practices: ['End User Computing', 'Security', 'Lifecycle Services'],
    industries: ['Education', 'Government', 'Health & Aged Care', 'Not-for-Profit'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Head of Digital Workplace', 'IT Manager', 'Chief Information Officer'],
    type: 'Core offer', owner: 'End User Computing', reviewed: 'Reviewed Jul 2026', proof: 'Lifecycle-ready',
    triggers: ['Device builds are inconsistent.', 'Endpoint posture is hard to report.', 'Support effort is rising.'],
    outputs: ['Endpoint baseline', 'Target management model', 'Migration waves'],
    actions: ['Open positioning', 'View device lifecycle', 'Find customer proof']
  },
  {
    id: 'avd',
    title: 'Azure Virtual Desktop Modernisation',
    tldr: 'Create a secure, scalable virtual desktop pattern for distributed or regulated workforces.',
    summary: 'A workload and user assessment followed by design, implementation and operational planning for a secure Azure Virtual Desktop platform.',
    timing: '8–12 weeks',
    practices: ['End User Computing', 'Hybrid Cloud', 'Security'],
    industries: ['Health & Aged Care', 'Government', 'Financial Services'],
    lifecycle: ['Consult', 'Procure', 'Implement', 'Operate'],
    audiences: ['Head of Infrastructure', 'Enterprise Architect', 'IT Manager'],
    type: 'Tier 2 offer', owner: 'End User Computing', reviewed: 'Reviewed Jun 2026', proof: 'Azure-aligned',
    triggers: ['Remote access is inconsistent.', 'Specialist apps need secure delivery.', 'Legacy VDI is costly.'],
    outputs: ['User and app assessment', 'Reference architecture', 'Migration plan'],
    actions: ['Open architecture', 'Use sizing questions', 'View migration path']
  },
  {
    id: 'copilot-deploy',
    title: 'Copilot Controlled Rollout & Adoption',
    tldr: 'Remediate readiness, pilot safely, enable users and establish measurable adoption.',
    summary: 'A controlled rollout that links information and identity remediation to pilot deployment, role-based enablement, governance and adoption measurement.',
    timing: '8–12 weeks',
    practices: ['Collaboration', 'Data & AI', 'Security'],
    industries: ['Government', 'Education', 'Financial Services', 'Mining'],
    lifecycle: ['Procure', 'Implement', 'Adopt', 'Operate'],
    audiences: ['Head of Digital Workplace', 'Chief Information Officer', 'IT Manager'],
    type: 'Core offer', owner: 'Collaboration + Data & AI', reviewed: 'Reviewed Aug 2026', proof: 'Adoption-led',
    triggers: ['Readiness is complete.', 'A pilot needs structure.', 'Leadership wants measurable value.'],
    outputs: ['Controlled pilot', 'Adoption plan', 'Measurement baseline'],
    actions: ['Open pilot plan', 'Use adoption play', 'Build measurement']
  }
];
