export type FocusKey = "networking" | "security" | "collaboration" | "ai";

export type FocusDefinition = {
  key: FocusKey;
  label: string;
  detail: string;
  resultTakeaway: string;
};

export type AdaptiveQuestion = {
  id: string;
  focus: FocusKey;
  rating: number;
  stage: string;
  context: string;
  prompt: string;
  options: [string, string, string];
  correctIndex: number;
  explanation: string;
  principle: string;
};

export const focusDefinitions: FocusDefinition[] = [
  {
    key: "networking",
    label: "Networking",
    detail: "Route the evidence",
    resultTakeaway: "AI-ready networks make evidence visible before they make change automatic.",
  },
  {
    key: "security",
    label: "Security",
    detail: "Contain the agent",
    resultTakeaway: "Agentic security starts with bounded identity, observable action, and a tested way to stop it.",
  },
  {
    key: "collaboration",
    label: "Collaboration",
    detail: "Protect human trust",
    resultTakeaway: "AI-assisted work remains trustworthy when authority, provenance, and human escalation stay clear.",
  },
  {
    key: "ai",
    label: "AI",
    detail: "Govern the outcome",
    resultTakeaway: "Useful AI autonomy depends on grounded evidence, explicit limits, and outcomes you can observe.",
  },
];

export const questionBank: AdaptiveQuestion[] = [
  {
    id: "net-0",
    focus: "networking",
    rating: 0,
    stage: "A signal disappears",
    context: "An edge AI service is slow, but the application dashboard is green. Network telemetry from one site stopped 20 minutes ago.",
    prompt: "What should you do first?",
    options: ["Scale the AI service while monitoring site latency", "Re-establish the missing network telemetry before changing capacity", "Restart the affected site connector and compare response times"],
    correctIndex: 1,
    explanation: "A green dashboard cannot clear a part of the path you can no longer see. Restore the evidence before changing the system.",
    principle: "Observability before intervention",
  },
  {
    id: "net-1",
    focus: "networking",
    rating: 1,
    stage: "Latency reaches users",
    context: "Employees report slow AI responses from one office. Compute utilisation and model response time look normal.",
    prompt: "Which check gives you the strongest next signal?",
    options: ["Compare the full user path against that office's normal baseline", "Trace requests from the application tier back to the model endpoint", "Measure loss and latency from the branch gateway to the cloud edge"],
    correctIndex: 0,
    explanation: "The symptom is local while compute is healthy. A path-level comparison can isolate access, WAN, DNS, or policy delay.",
    principle: "Follow the user path",
  },
  {
    id: "net-2",
    focus: "networking",
    rating: 2,
    stage: "A policy change is proposed",
    context: "An automation suggests a network policy change across every branch to reduce inference latency.",
    prompt: "What is the safest useful response?",
    options: ["Approve the change across lower-risk branches, then review telemetry", "Hold the change until every branch has a validated rollback", "Run a bounded canary with explicit success measures and automated rollback"],
    correctIndex: 2,
    explanation: "A canary tests the recommendation under real conditions without making every branch share the blast radius.",
    principle: "Bound the blast radius",
  },
  {
    id: "net-3",
    focus: "networking",
    rating: 3,
    stage: "The agent wants access",
    context: "A remediation agent needs temporary access to change quality-of-service policy during a high-priority incident.",
    prompt: "Which access design best supports the response?",
    options: ["A time-limited administrator credential with full session capture", "Scoped identity, approved actions, expiry, logging, and rollback", "Read-only access with manual elevation after remediation is confirmed"],
    correctIndex: 1,
    explanation: "Useful automation needs enough authority to act, but only inside an explicit scope, time window, and recovery path.",
    principle: "Bounded authority",
  },
  {
    id: "net-4",
    focus: "networking",
    rating: 4,
    stage: "Everything looks healthy",
    context: "Synthetic tests pass, yet real users intermittently fail when an AI assistant calls a data service across two clouds.",
    prompt: "Which investigation is most likely to expose the fault?",
    options: ["Correlate user, application, identity, and network events on one timeline", "Increase synthetic coverage at both cloud boundaries during a failure", "Capture packet traces from affected devices and compare failed sessions"],
    correctIndex: 0,
    explanation: "Cross-domain failures hide between healthy components. A shared timeline shows where identity, application, and network behaviour diverge.",
    principle: "Correlate across domains",
  },
  {
    id: "net-5",
    focus: "networking",
    rating: 5,
    stage: "Inference traffic surges",
    context: "An internal agent rollout causes unpredictable east-west traffic, delaying critical workloads without saturating total link capacity.",
    prompt: "What is the most complete engineering response?",
    options: ["Add capacity to the busiest links, then review whether latency clears", "Rate-limit non-critical AI flows during peak inference windows", "Classify flows, protect critical paths, observe contention, then tune policy and capacity"],
    correctIndex: 2,
    explanation: "Aggregate capacity can look healthy while specific workloads contend. Classification and path-level evidence make policy and capacity changes defensible.",
    principle: "Engineer for workload behaviour",
  },
  {
    id: "net-6",
    focus: "networking",
    rating: 6,
    stage: "The control plane is partly blind",
    context: "During a global incident, an agent recommends a route change that may restore service. Telemetry is incomplete in two regions.",
    prompt: "Which response best balances urgency and uncertainty?",
    options: ["Apply the change to the affected region with existing rollback controls and intensified telemetry", "Restore minimum evidence, then run a regional canary with live abort thresholds and rollback", "Fail traffic to healthy regions, freeze the affected routes, and reconstruct telemetry offline"],
    correctIndex: 1,
    explanation: "Incomplete evidence does not require paralysis, but it should prevent an irreversible global change. Restore the minimum signal and test reversibly.",
    principle: "Act proportionately to certainty",
  },

  {
    id: "sec-0",
    focus: "security",
    rating: 0,
    stage: "A prompt asks for privilege",
    context: "A user prompt tells an assistant to ignore policy and reveal an administrator token.",
    prompt: "What should the system do?",
    options: ["Refuse the request and record the attempt", "Quarantine the conversation and rotate the token named in the prompt", "Require the user to reauthenticate before evaluating the request"],
    correctIndex: 0,
    explanation: "Instructions inside a prompt must not override access policy. Refusal plus traceable evidence protects both the system and the investigation.",
    principle: "Policy outranks prompts",
  },
  {
    id: "sec-1",
    focus: "security",
    rating: 1,
    stage: "Privilege appears overnight",
    context: "A service identity used by an AI assistant suddenly gains write access to a production repository.",
    prompt: "What is the strongest first response?",
    options: ["Freeze repository writes and preserve the service identity session", "Suspend the new privilege and verify the complete change trail", "Rotate the service identity credential and monitor repository changes"],
    correctIndex: 1,
    explanation: "The unexpected privilege is the immediate exposure. Contain it, then use the change trail to determine intent and scope.",
    principle: "Contain, then investigate",
  },
  {
    id: "sec-2",
    focus: "security",
    rating: 2,
    stage: "One identity powers everything",
    context: "Several agents share one powerful service account across development and production.",
    prompt: "Which change reduces risk without stopping the program?",
    options: ["Keep the shared identity but restrict production actions to approved hours", "Split credentials by environment while retaining the shared workload identity", "Give each workload a scoped identity with separate environment permissions"],
    correctIndex: 2,
    explanation: "Workload-specific identities limit lateral movement and make every action attributable without removing useful automation.",
    principle: "Least privilege needs attribution",
  },
  {
    id: "sec-3",
    focus: "security",
    rating: 3,
    stage: "Untrusted content reaches a tool",
    context: "An agent reads a poisoned document that instructs it to call an approved administrative tool.",
    prompt: "Which control matters most at the point of action?",
    options: ["A tool layer that rechecks identity, policy, scope, and intent", "A retrieval filter that removes instructions from untrusted content", "A second model that approves every administrative tool call"],
    correctIndex: 0,
    explanation: "Prompt instructions are not a security boundary. Every consequential tool call needs independent, policy-bound authorisation.",
    principle: "Enforce at the tool boundary",
  },
  {
    id: "sec-4",
    focus: "security",
    rating: 4,
    stage: "Sensitive context expands",
    context: "A support agent is retrieving entire customer records when it only needs an entitlement status.",
    prompt: "What is the best design correction?",
    options: ["Encrypt the complete record and shorten how long it remains in context", "Retrieve and expose only the authorised fields needed for the task", "Mask sensitive fields in the response after the model completes its task"],
    correctIndex: 1,
    explanation: "Encryption protects data in transit, not overexposure during use. Minimise retrieval and enforce field-level access.",
    principle: "Minimise the agent's context",
  },
  {
    id: "sec-5",
    focus: "security",
    rating: 5,
    stage: "An agent is compromised",
    context: "A production agent is making valid but abnormal tool calls across hybrid infrastructure.",
    prompt: "Which sequence preserves control and evidence?",
    options: ["Pause the agent process, snapshot its environment, then review recent tool calls", "Rotate the agent credential, leave execution running, and increase monitoring", "Revoke its active authority, isolate its execution path, preserve traces, then scope impact"],
    correctIndex: 2,
    explanation: "Fast authority revocation stops further action; isolation and preserved traces keep the incident explainable and reportable.",
    principle: "Kill switch plus evidence",
  },
  {
    id: "sec-6",
    focus: "security",
    rating: 6,
    stage: "The traffic is encrypted",
    context: "An autonomous agent is moving sensitive data through approved encrypted channels. Endpoint alerts are inconclusive and time is short.",
    prompt: "Which response gives the team the strongest basis for containment?",
    options: ["Inspect selected egress traffic, correlate destinations, and block flows that breach behaviour thresholds", "Correlate workload identity, network behaviour, tool policy, and agent trace before containing authority", "Revoke the agent identity, preserve endpoint state, and reconstruct recent activity from available logs"],
    correctIndex: 1,
    explanation: "No single signal proves intent. Identity, behaviour, policy, and trace together support targeted containment without destroying the environment.",
    principle: "Join identity to behaviour",
  },

  {
    id: "collab-0",
    focus: "collaboration",
    rating: 0,
    stage: "A summary travels too far",
    context: "An AI meeting summary includes a confidential staffing decision and is about to be shared with external guests.",
    prompt: "What should happen first?",
    options: ["Redact the staffing paragraph and send the remaining summary to all attendees", "Restrict the summary to internal attendees and notify the meeting owner", "Pause distribution, verify each recipient's access, and review the complete summary"],
    correctIndex: 2,
    explanation: "Attendance does not equal permission to retain or redistribute every detail. Validate both content and audience before release.",
    principle: "Check audience at the boundary",
  },
  {
    id: "collab-1",
    focus: "collaboration",
    rating: 1,
    stage: "The assistant cannot help",
    context: "A customer-facing voice agent is uncertain which support queue owns an urgent issue.",
    prompt: "What is the best next action?",
    options: ["Route to the most likely specialist queue and flag the uncertainty", "Explain the uncertainty and hand off with context to human triage", "Keep the customer engaged while the agent gathers more diagnostic detail"],
    correctIndex: 1,
    explanation: "A transparent, context-rich hand-off protects the customer's time and keeps a human accountable for the uncertain decision.",
    principle: "Design the human hand-off",
  },
  {
    id: "collab-2",
    focus: "collaboration",
    rating: 2,
    stage: "The source is stale",
    context: "A workplace assistant drafts advice from an old project document that conflicts with the approved plan.",
    prompt: "Which fix addresses the root problem?",
    options: ["Show the source date with every answer and let employees judge freshness", "Prefer documents with the newest modification timestamp", "Ground answers in governed sources with version and freshness metadata"],
    correctIndex: 2,
    explanation: "Users cannot judge invisible source quality. Governed retrieval and visible provenance make freshness part of the answer.",
    principle: "Make provenance visible",
  },
  {
    id: "collab-3",
    focus: "collaboration",
    rating: 3,
    stage: "The workflow crosses teams",
    context: "An agent coordinates a customer response across sales, service, and engineering, but none owns the final decision.",
    prompt: "What must be made explicit before scaling it?",
    options: ["Decision ownership and escalation at each hand-off", "A shared service-level target with team-defined hand-offs", "One cross-functional operations queue for every unresolved decision"],
    correctIndex: 0,
    explanation: "Automation can move work, but it cannot resolve unclear accountability. Ownership and escalation have to travel with the workflow.",
    principle: "Automate flow, not ambiguity",
  },
  {
    id: "collab-4",
    focus: "collaboration",
    rating: 4,
    stage: "A meeting action becomes a change",
    context: "An assistant converts a meeting action into a production configuration change. The transcript is accurate, but approval was never explicit.",
    prompt: "Which design prevents this failure?",
    options: ["Require authorised approval at the boundary between suggestion and execution", "Require the assistant to quote the transcript passage that created the action", "Notify the service owner before execution and provide an automatic rollback window"],
    correctIndex: 0,
    explanation: "Accurate capture does not create authority. The system needs a deliberate approval boundary before a consequential action.",
    principle: "Separate intent from authority",
  },
  {
    id: "collab-5",
    focus: "collaboration",
    rating: 5,
    stage: "A familiar voice gives an order",
    context: "A convincing voice message from an executive directs an agent-assisted service desk to bypass a control during an outage.",
    prompt: "What should the workflow rely on?",
    options: ["Confirmation through the executive's known collaboration account", "Independent identity verification and a policy-bound exception process", "A second manager repeating the instruction on a recorded call"],
    correctIndex: 1,
    explanation: "Familiarity is not proof. High-impact exceptions need verified identity, explicit policy, attribution, and expiry.",
    principle: "Verify authority out of band",
  },
  {
    id: "collab-6",
    focus: "collaboration",
    rating: 6,
    stage: "Agents disagree",
    context: "Two authorised agents recommend conflicting actions for the same customer incident, and both cite valid policy.",
    prompt: "Which resolution keeps authority and accountability intact?",
    options: ["Use the narrower agent's recommendation, preserve both rationales, and monitor the customer outcome", "Apply the lower-risk recommendation, keep both agents active, and seek more evidence", "Apply authority precedence, preserve both rationales, and escalate unresolved conflict to the human owner"],
    correctIndex: 2,
    explanation: "Conflicting valid policies are a governance problem, not a reasoning contest. Precedence and human accountability resolve the ambiguity visibly.",
    principle: "Govern conflict, do not hide it",
  },

  {
    id: "ai-0",
    focus: "ai",
    rating: 0,
    stage: "The answer sounds certain",
    context: "An assistant confidently recommends a remediation step but cites no operational evidence.",
    prompt: "What should the engineer do?",
    options: ["Run the remediation in a sandbox and compare the predicted system impact", "Validate the recommendation against trusted operational evidence before acting", "Ask a second model to critique the recommendation and its assumptions"],
    correctIndex: 1,
    explanation: "Confidence is presentation, not proof. Consequential advice must be grounded in evidence you can inspect.",
    principle: "Evidence over eloquence",
  },
  {
    id: "ai-1",
    focus: "ai",
    rating: 1,
    stage: "Retries begin to spiral",
    context: "An agent repeatedly calls a slow service, increasing cost and making the outage worse.",
    prompt: "Which control should stop the loop?",
    options: ["A retry budget with back-off, circuit breaking, and escalation", "A higher-capacity service tier with the existing retry policy", "Request deduplication that lets the agent continue until recovery"],
    correctIndex: 0,
    explanation: "Autonomy needs explicit resource and retry limits. A circuit breaker stops local failure becoming system-wide pressure.",
    principle: "Bound the work, not just the access",
  },
  {
    id: "ai-2",
    focus: "ai",
    rating: 2,
    stage: "Retrieval returns old truth",
    context: "An operations assistant uses a superseded runbook even though the current version exists.",
    prompt: "What should the system expose with every answer?",
    options: ["Document title, retrieval score, and model confidence", "Source provenance, version, and freshness", "The relevant source passage and time of the user's request"],
    correctIndex: 1,
    explanation: "A grounded answer is only as useful as its source. Provenance and freshness let both the system and the operator reject stale truth.",
    principle: "Govern the knowledge path",
  },
  {
    id: "ai-3",
    focus: "ai",
    rating: 3,
    stage: "A document becomes an instruction",
    context: "An agent treats text inside an untrusted document as authority to call an internal tool.",
    prompt: "Which architecture best limits the damage?",
    options: ["Separate instructions from data and enforce policy again at every tool call", "Sanitise documents and block content matching known attack patterns", "Use a second agent to inspect each proposed tool call for malicious intent"],
    correctIndex: 0,
    explanation: "Untrusted content must remain data. Independent authorisation at the action layer prevents a poisoned context becoming authority.",
    principle: "Context is not authority",
  },
  {
    id: "ai-4",
    focus: "ai",
    rating: 4,
    stage: "Quality drifts quietly",
    context: "An agent still passes technical health checks, but its resolution quality has declined over several weeks.",
    prompt: "Which signal would have revealed this earliest?",
    options: ["Model latency, refusal rate, and infrastructure saturation by release", "User sentiment and escalation volume after each workflow change", "Versioned outcome measures linked to model, prompt, data, and workflow changes"],
    correctIndex: 2,
    explanation: "Service health does not measure decision quality. Versioned outcome telemetry makes gradual degradation attributable.",
    principle: "Observe outcomes, not uptime alone",
  },
  {
    id: "ai-5",
    focus: "ai",
    rating: 5,
    stage: "Placement becomes a control",
    context: "A field AI use case handles sensitive data, needs low latency, and must keep working through cloud disruption.",
    prompt: "How should edge versus cloud placement be decided?",
    options: ["Prioritise data residency and resilience, then optimise latency within those constraints", "Score sensitivity, latency, resilience, operability, and cost for each workload component", "Prioritise latency and cost, then add compensating controls for sensitive data"],
    correctIndex: 1,
    explanation: "Placement is an outcome and control decision, not a slogan. Different parts of the workload may need different locations.",
    principle: "Place for the outcome",
  },
  {
    id: "ai-6",
    focus: "ai",
    rating: 6,
    stage: "The agent can act, but evidence is incomplete",
    context: "An autonomous operations agent predicts a cascading failure. Acting could prevent it; acting globally could also cause an outage.",
    prompt: "Which action should be authorised?",
    options: ["Approve a regional canary with automated rollback, continuous telemetry, and a mandatory post-action review", "Require two-person approval for a staged global change with live telemetry and rollback gates", "Authorise a bounded regional canary with live abort thresholds, full trace, and an independent kill switch"],
    correctIndex: 2,
    explanation: "The response preserves useful speed while matching authority to uncertainty and making the action observable and reversible.",
    principle: "Scale autonomy with evidence",
  },
];

export function difficultyLabel(rating: number) {
  if (rating <= 1) return "Easy";
  if (rating <= 4) return "Expert";
  return "Impossible";
}

export function questionsForFocus(focus: FocusKey) {
  return questionBank.filter((question) => question.focus === focus);
}
