import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useLocation } from "wouter";
import { QRCodeSVG } from "qrcode.react";
import { AlertTriangle, ArrowRight, Check, Copy, Download, Eye, LockKeyhole, Monitor, Play, RotateCcw, ShieldCheck, Users } from "lucide-react";
import "./decision-room.css";

type Round = { label:string; facts:string[]; task:string; options?: readonly (readonly [string,string,string])[] };
type ConsoleData = {
  session:{id:string;joinCode:string;name:string;variant:string;status:string;activeRound:number;resultsVisible:boolean;revision:number;roundStartedAt:string|null};
  scenario:{title:string;round:Round}; counts:{notJoined:number;reading:number;debating:number;locked:number};
  teams:{id:string;displayName:string;state:string}[];
  results:null|{options:Record<string,number>;confidence:{low:number|null;high:number|null;median:number|null};featured:{id:string;action:string;tradeoff:string;reversalEvidence:string;confidence:number|null}[]};
  decisions?: Decision[];
};
type Decision={id:string;teamId:string;roundNo:number;optionKey:string|null;action:string;acceptedTradeoff:string;reversalEvidence:string;confidence:number|null;isLocked:boolean;isFeatured:boolean};
type ParticipantData={session:{id:string;name:string;status:string;activeRound:number;revision:number};team:{id:string;displayName:string;state:string};scenario:{title:string;subtitle:string;brief:string;objective:string;round:Round};decision:Decision|null};

const API="/api/decision-room";
async function request<T>(url:string, options:RequestInit={}) {
  const response=await fetch(url,options); const body=await response.json().catch(()=>({message:response.statusText}));
  if(!response.ok) throw new Error(body.message||"Request failed"); return body as T;
}
const json=(body:unknown, headers:Record<string,string>={})=>({method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)});
function useClock(started:string|null|undefined){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);if(!started)return"--:--";const left=12*60-Math.floor((now-new Date(started).getTime())/1000);const abs=Math.abs(left);return `${left<0?"+":""}${Math.floor(abs/60).toString().padStart(2,"0")}:${(abs%60).toString().padStart(2,"0")}`;}
function Frame({children,wide=false}:{children:ReactNode;wide?:boolean}){return <main className={`dr-shell ${wide?"dr-wide":""}`}><header className="dr-brand"><div className="dr-mark">D<span>#</span>3</div><div><strong>DECISION ROOM</strong><small>WHEN THE AGENT ACTS</small></div></header>{children}<footer>Observe · govern · secure</footer></main>}
function ErrorText({message}:{message:string}){return message?<p className="dr-error"><AlertTriangle size={18}/>{message}</p>:null}

function Landing({presetCode}:{presetCode?:string}){
  const [,navigate]=useLocation(); const [mode,setMode]=useState<"join"|"facilitate"|"display">("join"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [joinCode,setJoinCode]=useState(presetCode||""); const [teamCode,setTeamCode]=useState("");
  const [adminKey,setAdminKey]=useState(localStorage.getItem("decision-room-admin-key")||""); const [variant,setVariant]=useState("enterprise"); const [tableCount,setTableCount]=useState(6);
  const [sessionId,setSessionId]=useState(""); const [displayToken,setDisplayToken]=useState("");
  async function join(){setBusy(true);setError("");try{const data=await request<{teamToken:string;joinCode:string}>(`${API}/join`,json({joinCode,teamCode}));localStorage.setItem(`decision-room-team:${data.joinCode}`,data.teamToken);navigate(`/decision-room/session/${data.joinCode}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function create(){setBusy(true);setError("");try{const data=await request<{sessionId:string;joinCode:string;displayToken:string}>(`${API}/sessions`,json({name:"When the agent acts",variant,tableCount},{"x-admin-key":adminKey}));localStorage.setItem("decision-room-admin-key",adminKey);localStorage.setItem(`decision-room-display:${data.sessionId}`,data.displayToken);navigate(`/decision-room/admin/${data.sessionId}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function openDisplay(){localStorage.setItem(`decision-room-display:${sessionId}`,displayToken);navigate(`/decision-room/console/${sessionId}`)}
  return <Frame><section className="dr-hero"><span className="dr-kicker">LIVE TABLETOP INSTRUMENT</span><h1>Make the room’s decisions visible.</h1><p>Each table records one defensible call. Adam controls the reveals. Richard listens for the reasoning that holds up when the facts change.</p></section>
    <nav className="dr-tabs" aria-label="Choose view"><button className={mode==="join"?"active":""} onClick={()=>setMode("join")}><Users/>Join a table</button><button className={mode==="facilitate"?"active":""} onClick={()=>setMode("facilitate")}><ShieldCheck/>Facilitate</button><button className={mode==="display"?"active":""} onClick={()=>setMode("display")}><Monitor/>Open console</button></nav>
    <section className="dr-card dr-form">
      {mode==="join"&&<><h2>Join your table</h2><label>Room code<input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="ABC123" maxLength={8}/></label><label>Table code<input value={teamCode} onChange={e=>setTeamCode(e.target.value)} placeholder="1" maxLength={12}/></label><button className="dr-primary" disabled={busy||!joinCode||!teamCode} onClick={join}>Join room <ArrowRight/></button></>}
      {mode==="facilitate"&&<><h2>Create a live room</h2><label>Facilitator key<input type="password" value={adminKey} onChange={e=>setAdminKey(e.target.value)} /></label><div className="dr-grid-two"><label>Audience<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="enterprise">Enterprise · Project Atlas</option><option value="government">Government · Civic Assist</option></select></label><label>Tables<input type="number" min={2} max={50} value={tableCount} onChange={e=>setTableCount(Number(e.target.value))}/></label></div><button className="dr-primary" disabled={busy||!adminKey} onClick={create}>Create room <ArrowRight/></button></>}
      {mode==="display"&&<><h2>Open a presenter console</h2><label>Session ID<input value={sessionId} onChange={e=>setSessionId(e.target.value)} /></label><label>Display token<input type="password" value={displayToken} onChange={e=>setDisplayToken(e.target.value)} /></label><button className="dr-primary" disabled={!sessionId||!displayToken} onClick={openDisplay}>Open console <Monitor/></button></>}
      <ErrorText message={error}/>
    </section></Frame>
}

function Participant({code}:{code:string}){
  const token=localStorage.getItem(`decision-room-team:${code}`)||""; const [,navigate]=useLocation(); const [data,setData]=useState<ParticipantData|null>(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false);
  const [optionKey,setOptionKey]=useState<string|null>(null),[action,setAction]=useState(""),[tradeoff,setTradeoff]=useState(""),[reversal,setReversal]=useState(""),[confidence,setConfidence]=useState(3);
  async function load(){if(!token){navigate(`/decision-room/join/${code}`);return}try{const next=await request<ParticipantData>(`${API}/sessions/${code}/participant`,{headers:{"x-team-token":token}});setData(next);setError("")}catch(e){setError((e as Error).message)}}
  useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[code,token]);
  useEffect(()=>{if(!data)return;const d=data.decision;setOptionKey(d?.optionKey??null);setAction(d?.action??"");setTradeoff(d?.acceptedTradeoff??"");setReversal(d?.reversalEvidence??"");setConfidence(d?.confidence??3)},[data?.session.activeRound,data?.decision?.id]);
  async function save(lock:boolean){if(!data)return;setSaving(true);setError("");try{await request(`${API}/sessions/${code}/decision`,{...json({roundNo:data.session.activeRound,optionKey,action,acceptedTradeoff:tradeoff,reversalEvidence:reversal,confidence,lock},{"x-team-token":token}),method:"PUT"});await load()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  if(!data)return <Frame><section className="dr-card"><h2>Connecting to the room…</h2><ErrorText message={error}/></section></Frame>;
  const locked=data.decision?.isLocked; const live=data.session.status==="live";
  return <Frame><div className="dr-session-head"><div><span className="dr-kicker">{data.team.displayName.toUpperCase()} · ROUND {data.session.activeRound}</span><h1>{data.scenario.title}</h1><p>{data.scenario.subtitle}</p></div><span className={`dr-status ${locked?"locked":""}`}>{locked?<><LockKeyhole/>Locked</>:data.team.state}</span></div>
    {!live&&<section className="dr-card dr-wait"><h2>{data.session.status==="ended"?"The room has closed":"Waiting for Adam to open the exercise"}</h2><p>{data.scenario.objective}</p></section>}
    {live&&<><section className="dr-card"><span className="dr-kicker">{data.scenario.round.label}</span>{data.scenario.round.facts.map((f,i)=><div className="dr-fact" key={f}><b>{String(i+1).padStart(2,"0")}</b><p>{f}</p></div>)}<h2 className="dr-task">{data.scenario.round.task}</h2></section>
      <section className="dr-card dr-form"><p className="dr-rule">30 seconds alone. Hear one concern from every person. Then agree the response.</p>
      {data.scenario.round.options&&<div className="dr-options">{data.scenario.round.options.map(o=><button className={optionKey===o[0]?"selected":""} onClick={()=>{setOptionKey(o[0]);setAction(o[1])}} disabled={locked} key={o[0]}><b>{o[0]}</b><span><strong>{o[1]}</strong><small>{o[2]}</small></span></button>)}</div>}
      <label>Action<textarea value={action} onChange={e=>setAction(e.target.value)} maxLength={240} disabled={locked} placeholder="What are you doing now?"/></label><label>Accepted trade-off<textarea value={tradeoff} onChange={e=>setTradeoff(e.target.value)} maxLength={240} disabled={locked} placeholder="What consequence are you knowingly accepting?"/></label><label>Evidence that would change your decision<textarea value={reversal} onChange={e=>setReversal(e.target.value)} maxLength={240} disabled={locked} placeholder="What would make you reverse this call?"/></label>
      <label>Confidence · {confidence}<input className="dr-range" type="range" min={1} max={5} value={confidence} onChange={e=>setConfidence(Number(e.target.value))} disabled={locked}/><span className="dr-range-labels"><small>Very uncertain</small><small>Strongly supported</small></span></label>
      {!locked&&<div className="dr-actions"><button onClick={()=>save(false)} disabled={saving||action.length<2||tradeoff.length<2||reversal.length<2}>Save draft</button><button className="dr-primary" onClick={()=>save(true)} disabled={saving||action.length<2||tradeoff.length<2||reversal.length<2}>Lock response <LockKeyhole/></button></div>}{locked&&<div className="dr-locked"><Check/>Response locked. Stay with your table for the reveal.</div>}<ErrorText message={error}/></section></>}
  </Frame>
}

function Console({id}:{id:string}){
  const queryToken=new URLSearchParams(location.search).get("displayToken");const displayToken=queryToken||localStorage.getItem(`decision-room-display:${id}`)||"";const [data,setData]=useState<ConsoleData|null>(null);const [error,setError]=useState("");
  async function load(){try{setData(await request(`${API}/sessions/${id}/console?displayToken=${encodeURIComponent(displayToken)}`));setError("")}catch(e){setError((e as Error).message)}}
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[id,displayToken]);const clock=useClock(data?.session.roundStartedAt);
  if(!data)return <Frame wide><section className="dr-card"><h2>Opening presenter console…</h2><ErrorText message={error}/></section></Frame>;
  const total=data.teams.length, joined=total-data.counts.notJoined;
  return <Frame wide><section className="dr-console-head"><div><span className="dr-kicker">{data.session.name.toUpperCase()}</span><h1>{data.scenario.title}</h1><p>Room <strong>{data.session.joinCode}</strong> · Round {data.session.activeRound} of 3</p></div><div className="dr-clock"><small>ROUND CLOCK</small><strong>{clock}</strong></div></section>
    <section className="dr-metrics"><Metric label="Joined" value={`${joined}/${total}`}/><Metric label="Reading" value={data.counts.reading}/><Metric label="Debating" value={data.counts.debating}/><Metric label="Locked" value={data.counts.locked} accent/></section>
    <section className="dr-console-grid"><div className="dr-card"><span className="dr-kicker">CURRENT FACTS</span>{data.scenario.round.facts.map((f,i)=><div className="dr-fact" key={f}><b>{String(i+1).padStart(2,"0")}</b><p>{f}</p></div>)}<h2 className="dr-task">{data.scenario.round.task}</h2></div><div className="dr-card"><span className="dr-kicker">TABLE PROGRESS</span><div className="dr-team-grid">{data.teams.map(t=><div className={`dr-team ${t.state}`} key={t.id}><strong>{t.displayName}</strong><small>{t.state.replace("_"," ")}</small></div>)}</div></div></section>
    {data.results?<section className="dr-results"><div className="dr-card"><span className="dr-kicker">ROOM PATTERN</span>{data.session.activeRound===1&&<div className="dr-bars">{Object.entries(data.results.options).map(([k,v])=><div key={k}><b>{k}</b><span><i style={{width:`${Math.max(4,(v/Math.max(1,data.counts.locked))*100)}%`}}/></span><strong>{v}</strong></div>)}</div>}<p>Confidence range <strong>{data.results.confidence.low??"–"}–{data.results.confidence.high??"–"}</strong> · median <strong>{data.results.confidence.median??"–"}</strong></p></div>{data.results.featured.map(f=><div className="dr-card dr-quote" key={f.id}><span>SELECTED REASONING</span><strong>{f.action}</strong><p>Trade-off: {f.tradeoff}</p><small>Would reverse if: {f.reversalEvidence}</small></div>)}</section>:<p className="dr-console-note">Responses remain private until Adam publishes the room pattern.</p>}<ErrorText message={error}/></Frame>
}
function Metric({label,value,accent=false}:{label:string;value:string|number;accent?:boolean}){return <div className={`dr-metric ${accent?"accent":""}`}><small>{label}</small><strong>{value}</strong></div>}

function Admin({id}:{id:string}){
  const [key,setKey]=useState(localStorage.getItem("decision-room-admin-key")||"");const displayToken=localStorage.getItem(`decision-room-display:${id}`)||"";const [data,setData]=useState<ConsoleData|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function load(){if(!key)return;try{setData(await request(`${API}/sessions/${id}/admin`,{headers:{"x-admin-key":key}}));setError("")}catch(e){setError((e as Error).message)}}useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[id,key]);
  async function act(body:unknown){setBusy(true);try{await request(`${API}/sessions/${id}/actions`,json(body,{"x-admin-key":key}));await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function exportCsv(){setError("");try{const response=await fetch(`${API}/sessions/${id}/export`,{headers:{"x-admin-key":key}});if(!response.ok){const body=await response.json();throw new Error(body.message||"Export failed")}const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download=`decision-room-${data?.session.joinCode||"export"}.csv`;anchor.click();URL.revokeObjectURL(url)}catch(e){setError((e as Error).message)}}
  if(!key)return <Frame><section className="dr-card dr-form"><h2>Facilitator access</h2><label>Facilitator key<input type="password" onChange={e=>setKey(e.target.value)}/></label><button className="dr-primary" onClick={()=>localStorage.setItem("decision-room-admin-key",key)}>Continue</button></section></Frame>;
  if(!data)return <Frame><section className="dr-card"><h2>Opening facilitator controls…</h2><ErrorText message={error}/></section></Frame>;
  const joinUrl=`${location.origin}/decision-room/join/${data.session.joinCode}`;const current=(data.decisions||[]).filter(d=>d.roundNo===data.session.activeRound);
  return <Frame wide><section className="dr-admin-head"><div><span className="dr-kicker">FACILITATOR CONTROLS</span><h1>{data.scenario.title}</h1><p>Room <strong>{data.session.joinCode}</strong> · {data.session.status} · round {data.session.activeRound}</p></div><div className="dr-qr"><QRCodeSVG value={joinUrl} size={118} bgColor="#ffffff" fgColor="#000025"/><button onClick={()=>navigator.clipboard.writeText(joinUrl)}><Copy/>Copy join link</button></div></section>
    <section className="dr-control-bar"><button onClick={()=>act({action:"start"})} disabled={busy||data.session.status==="live"}><Play/>Start</button><button onClick={()=>act({action:"publish"})} disabled={busy||data.session.resultsVisible}><Eye/>Publish pattern</button><button className="dr-primary" onClick={()=>act({action:"advance"})} disabled={busy||data.session.activeRound===3}>Next reveal <ArrowRight/></button><a className="dr-button" target="_blank" rel="noreferrer" href={`/decision-room/console/${id}?displayToken=${encodeURIComponent(displayToken)}`}><Monitor/>Open console</a><button onClick={exportCsv}><Download/>Export CSV</button><button onClick={()=>act({action:"end"})} disabled={busy}>End</button><button className="danger" onClick={()=>confirm("Reset this room and remove all responses?")&&act({action:"reset"})} disabled={busy}><RotateCcw/>Reset</button></section>
    <section className="dr-metrics"><Metric label="Not joined" value={data.counts.notJoined}/><Metric label="Reading" value={data.counts.reading}/><Metric label="Debating" value={data.counts.debating}/><Metric label="Locked" value={data.counts.locked} accent/></section>
    <section className="dr-admin-grid"><div className="dr-card"><h2>Tables</h2>{data.teams.map(t=><div className="dr-admin-row" key={t.id}><span><strong>{t.displayName}</strong><small>{t.state}</small></span>{t.state==="locked"&&<button onClick={()=>act({action:"reopen",teamId:t.id})}>Reopen</button>}</div>)}</div><div className="dr-card"><h2>Current responses</h2>{current.length===0?<p>No responses yet.</p>:current.map(d=><div className="dr-response" key={d.id}><strong>{d.action||"Draft"}</strong><p>{d.acceptedTradeoff}</p><small>Reverse if: {d.reversalEvidence} · confidence {d.confidence??"–"}</small><button onClick={()=>act({action:"feature",decisionId:d.id,featured:!d.isFeatured})}>{d.isFeatured?"Remove from console":"Select for console"}</button></div>)}</div></section><ErrorText message={error}/></Frame>
}

export default function DecisionRoom(){const [path]=useLocation();const parts=path.split("/").filter(Boolean);if(parts[1]==="join")return <Landing presetCode={parts[2]}/>;if(parts[1]==="session"&&parts[2])return <Participant code={parts[2].toUpperCase()}/>;if(parts[1]==="console"&&parts[2])return <Console id={parts[2]}/>;if(parts[1]==="admin"&&parts[2])return <Admin id={parts[2]}/>;return <Landing/>}
