-- ============================================================================
-- DATA#3 CISCO LIVE - TRIVIA MIGRATION TO 4 CATEGORIES
-- ============================================================================
-- This SQL file migrates from 5 categories to 4 new categories with updated
-- trivia questions.
--
-- New Categories:
--   1. NETWORKING (25 questions)
--   2. SECURITY (18 questions)
--   3. COLLABORATION (18 questions)
--   4. DATA_CENTER (20 questions)
--
-- Total: 81 trivia questions
--
-- Table: trivia_items
-- Columns: id, category, stem, choices (array), correct_index, drop_index,
--          hint_9s, explanation, difficulty, active, version
-- ============================================================================

-- Step 1: Clear existing trivia questions
DELETE FROM trivia_items;

-- ============================================================================
-- NETWORKING CATEGORY (25 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, correct_index, drop_index, hint_9s, explanation, difficulty, active, version) VALUES
('net-001', 'NETWORKING', 'Which two Catalyst switch models include dedicated data processing units?', ARRAY['9400X and 9500X', '9300 and 9200', '9000 and Over 9000'], 0, 1, 'Think X marks the spot for extreme performance.', 'The Catalyst 9400X and 9500X include dedicated DPUs (Data Processing Units) that enable advanced security and analytics at the switching layer without impacting forwarding performance.', 2, true, 1),
('net-002', 'NETWORKING', 'Which Nexus switch series includes models with DPUs for AI workloads?', ARRAY['Nexus 9300', 'Nexus 7000', 'Nexus 42'], 0, 1, 'It''s in the 9000 family, but lower than 9500.', 'The Nexus 9300 series includes models with dedicated DPUs designed to accelerate AI workloads, provide inline security, and handle telemetry processing without affecting network throughput.', 2, true, 1),
('net-003', 'NETWORKING', 'What network speed optics did Cisco announce for AI-ready data centers?', ARRAY['800G', '400G', '88 MPH'], 0, 1, 'Double what you think is already really fast.', 'Cisco announced 800 Gigabit Ethernet optics for AI-ready data centers, supporting the massive bandwidth requirements of GPU-to-GPU communication in AI training clusters.', 2, true, 1),
('net-004', 'NETWORKING', 'What is Cisco''s new switch series designed for AI data centers with NVIDIA GPU integration?', ARRAY['Nexus HyperFabric', 'Catalyst AI', 'Cisco SkyNet'], 0, 1, 'It''s Hyper-focused on fabric connectivity.', 'Nexus HyperFabric is Cisco''s purpose-built switching platform for AI data centers, featuring deep integration with NVIDIA GPUs and optimized for ultra-low latency AI workloads.', 2, true, 1),
('net-005', 'NETWORKING', 'Which fabrics does the Unified Nexus Dashboard consolidate?', ARRAY['ACI, VXLAN, and traditional networks', 'Campus, WAN, and Data Center', 'Cotton, Silk, and Polyester'], 0, 1, 'Think about the underlying network protocols, not locations.', 'The Unified Nexus Dashboard consolidates management of ACI (Application Centric Infrastructure), VXLAN-based networks, and traditional switching fabrics into a single interface.', 2, true, 1),
('net-006', 'NETWORKING', 'What security capability do Smart Switches deliver at line rate?', ARRAY['DPU-based firewalling', 'AI threat detection', 'Enterprise Trust Issues'], 0, 1, 'It uses those special processing units we keep mentioning.', 'Smart Switches use embedded DPUs to deliver line-rate firewall inspection on every port without performance degradation, extending zero-trust security to the switching layer.', 2, true, 1),
('net-007', 'NETWORKING', 'Which Cisco technology provides AI-driven security enforcement across distributed networks?', ARRAY['Hypershield', 'Hyperfabric', 'Hypercolour'], 0, 1, 'It''s hyper-focused on distributed security.', 'Cisco Hypershield provides AI-driven security enforcement across distributed networks using dual data planes and compensating controls to protect against threats at massive scale.', 2, true, 1),
('net-008', 'NETWORKING', 'What Cisco platform combines routing, SD-WAN, and firewall in a single appliance?', ARRAY['Cisco 8000 Secure Router', 'ISR 4000 Series', 'Swiss Army Router'], 0, 1, 'It''s in the 8000 family and it''s Secure.', 'The Cisco 8000 Secure Router series combines high-performance routing, SD-WAN capabilities, and next-generation firewall functions in a single platform for simplified branch deployments.', 2, true, 1),
('net-009', 'NETWORKING', 'What is Cisco''s AI-based collaborative workspace for advanced troubleshooting?', ARRAY['AI Canvas', 'Webex AI Assistant', 'Clippy 2.0'], 0, 1, 'It helps you see with a thousand perspectives.', 'ThousandEyes Copilot is an AI-powered collaborative workspace that helps network teams diagnose complex issues faster by providing intelligent insights and automated troubleshooting recommendations.', 2, true, 1),
('net-010', 'NETWORKING', 'What does Cisco call its unified security strategy including Secure Firewall and Hypershield?', ARRAY['Hybrid Mesh Firewall', 'Unified Security Platform', 'Security Spaghetti Junction'], 0, 1, 'It''s a mesh that works in hybrid environments.', 'Hybrid Mesh Firewall is Cisco''s strategy to unify security enforcement across Cisco Secure Firewall, Hypershield, Meraki, ASA, and third-party firewalls under a single policy framework.', 2, true, 1),
('net-011', 'NETWORKING', 'Which technology partnership enabled Cisco to add DPUs to switches?', ARRAY['NVIDIA', 'Intel', 'AMD'], 0, 1, 'The same company famous for GPUs also makes DPUs.', 'Cisco partnered with NVIDIA to integrate NVIDIA BlueField DPUs into switches, enabling advanced processing capabilities for security, telemetry, and AI workload acceleration.', 2, true, 1),
('net-012', 'NETWORKING', 'What type of security does Cisco''s Secure Router series include against quantum threats?', ARRAY['Post-quantum cryptography', 'Quantum-resistant encryption', 'Schrödinger Pro'], 0, 1, 'It comes after quantum computing becomes a threat.', 'Cisco''s Secure Router series includes post-quantum cryptography algorithms designed to protect against future attacks from quantum computers that could break current encryption standards.', 2, true, 1),
('net-013', 'NETWORKING', 'What does Cisco call its vision of using AI agents to diagnose network issues proactively?', ARRAY['Agentic AI', 'Synthetic Support Desk', 'Network Psychics United'], 0, 1, 'The agents are doing the work for you.', 'Agentic AI is Cisco''s vision where AI agents autonomously diagnose, predict, and resolve network issues before they impact users, transforming network operations.', 2, true, 1),
('net-014', 'NETWORKING', 'What is the maximum switching capacity of the Catalyst 9000X series?', ARRAY['25.6 Tbps', '25.6 Gbps', '25.6 Mbps'], 0, 1, 'Think big. Seriously, big.', 'The Catalyst 9000X series delivers up to 25.6 Terabits per second of switching capacity, supporting high-density, high-performance enterprise and data center deployments.', 2, true, 1),
('net-015', 'NETWORKING', 'Which Catalyst switch platform supports Universal PoE for high-power devices?', ARRAY['Catalyst 9000 Series', 'Catalyst 3850 Series', 'Catalyst Unlimited Power Edition'], 0, 1, 'It''s the current flagship 9000 family.', 'The Catalyst 9000 Series supports Universal PoE (UPoE) delivering up to 60W per port, enabling high-power devices like PTZ cameras, wireless access points, and digital displays.', 2, true, 1),
('net-016', 'NETWORKING', 'What power budget can Cisco''s Ultra PoE switches deliver per port?', ARRAY['90W', '60W', '1.21 Gigawatts'], 0, 1, 'It''s 50% more than Universal PoE.', 'Cisco''s Ultra PoE (UPoE+) switches can deliver up to 90 watts per port, supporting the most power-hungry devices like LED lighting, building automation, and advanced PTZ cameras.', 2, true, 1),
('net-017', 'NETWORKING', 'Which Cisco switch operating system powers both Catalyst and Nexus platforms?', ARRAY['IOS-XE', 'NX-OS', 'S-OS'], 0, 1, 'It''s the eXtended Edition of a classic.', 'Cisco IOS XE is the modern operating system powering Catalyst switches, while select Nexus platforms also support it, providing consistency across enterprise and data center environments.', 2, true, 1),
('net-018', 'NETWORKING', 'What is the name of Cisco''s intent-based networking platform for enterprise networks?', ARRAY['Cisco Catalyst Center', 'Cisco Prime Infrastructure', 'Cisco SkyNet'], 0, 1, 'It understands the DNA of your network.', 'Cisco DNA Center is the intent-based networking platform that automates network provisioning, policy enforcement, and assurance across the enterprise using AI and machine learning.', 2, true, 1),
('net-019', 'NETWORKING', 'Which Catalyst switch series is optimized for cloud-scale deployments?', ARRAY['Cisco Catalyst 9000 Series', 'Cisco Nexus 9000 Series', 'Cisco Nimbus 9000 Series'], 0, 1, 'The highest number in the current lineup.', 'The Catalyst 9000 Series is purpose-built for cloud-scale deployments with programmable ASICs, telemetry, automation APIs, and the performance needed for modern hybrid cloud architectures.', 2, true, 1),
('net-020', 'NETWORKING', 'What switching technology enables lossless Ethernet for storage and AI workloads?', ARRAY['Priority Flow Control', 'Quality of Service', 'No Packet Left Behind Protocol'], 0, 1, 'It controls the flow with priority.', 'Priority Flow Control (PFC) enables lossless Ethernet by pausing transmission on congested queues, essential for storage protocols like iSCSI and AI workloads that cannot tolerate packet loss.', 2, true, 1),
('net-021', 'NETWORKING', 'Which Nexus platform is designed specifically for spine-leaf architectures?', ARRAY['Nexus 9000 Series', 'Nexus 7000 Series', 'Nexus 5000 Series'], 0, 1, 'It''s the 9000 series built for modern fabrics.', 'The Nexus 9000 series is purpose-built for spine-leaf data center architectures, offering ultra-low latency, high bandwidth, and support for both ACI and NX-OS modes.', 2, true, 1),
('net-022', 'NETWORKING', 'What is the total throughput capacity of the Nexus 9000 series flagship model?', ARRAY['64 Tbps', '32 Tbps', '16 Tbps'], 0, 1, 'Double what seems already unreasonably fast.', 'The Nexus 9000 series flagship models deliver up to 64 Terabits per second of throughput, supporting the most demanding hyperscale data center and AI infrastructure requirements.', 2, true, 1),
('net-023', 'NETWORKING', 'Which Cisco switching feature provides microsecond-level network telemetry?', ARRAY['Streaming Telemetry', 'NetFlow', 'Gossip Protocol'], 0, 1, 'It streams data in real time, not in batches.', 'Streaming Telemetry provides microsecond-level visibility into network behavior by continuously pushing real-time data, unlike traditional polling methods, enabling faster anomaly detection.', 2, true, 1),
('net-024', 'NETWORKING', 'What technology allows Cisco switches to segment networks without VLANs?', ARRAY['TrustSec', 'VRF', 'VLAN-Free Zones'], 0, 1, 'It''s about trust and security, not VLANs.', 'Cisco TrustSec uses Security Group Tags (SGTs) to segment networks based on identity rather than IP addresses or VLANs, simplifying policy enforcement and improving security.', 2, true, 1),
('net-025', 'NETWORKING', 'Which Catalyst series includes Wi-Fi 7 integrated access points?', ARRAY['Catalyst 9130', 'Catalyst 9800', 'Catalyst 404'], 0, 1, 'It''s the access point series, not the wireless controller.', 'The Catalyst 9130 series access points support Wi-Fi 7 (802.11be), delivering multi-gigabit speeds, ultra-low latency, and support for dense, high-performance wireless environments.', 2, true, 1);

-- ============================================================================
-- SECURITY CATEGORY (18 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, correct_index, drop_index, hint_9s, explanation, difficulty, active, version) VALUES
('sec-001', 'SECURITY', 'This framework includes distributed firewalls and Hypershield:', ARRAY['Hybrid Mesh Firewall', 'Hybrid Cloud Defense Matrix', 'Firewall Farm Federation'], 0, 1, 'This portfolio adds enforcement points across diverse environments.', 'Cisco''s Hybrid Mesh Firewall is a distributed security fabric that includes Cisco and third-party firewalls, Cisco Hypershield, and Cisco Secure Workload for zero-trust segmentation.', 2, true, 1),
('sec-002', 'SECURITY', 'What does ZTNA stand for?', ARRAY['Zero Trust Network Access', 'Zero Threat Network Architecture', 'Zombies That Never Attack'], 0, 1, 'Ensures identity-driven access for users, devices, and AI agents.', 'Universal ZTNA stands for Universal Zero Trust Network Access, ensuring seamless, identity-driven access while simplifying secure connectivity across hybrid environments.', 2, true, 1),
('sec-003', 'SECURITY', 'What is the per-RU performance density of the Cisco Secure Firewall 6100?', ARRAY['200 Gbps', '20 Gbps', '2 Gbps'], 0, 1, 'The biggest number is usually correct!', 'The Cisco Secure Firewall 6100 Series delivers 200 Gbps per rack unit, providing the highest performance density for data center firewalling.', 2, true, 1),
('sec-004', 'SECURITY', 'Which branch firewall series has integrated SD-WAN?', ARRAY['200 Series', '8000 Series', '404 Series'], 0, 1, 'Delivers up to 3x price-performance compared to competition.', 'The Cisco Secure Firewall 200 Series is designed for distributed branches with integrated SD-WAN at up to 3x price-performance compared to competition.', 2, true, 1),
('sec-005', 'SECURITY', 'Name the Cisco Security Cloud Control unified policy engine:', ARRAY['Mesh Policy Engine', 'Identity Service Engine', 'Internal Combustion Engine'], 0, 1, 'Everything connects to everything.', 'The Mesh Policy Engine enables teams to define a single intent-based policy enforced across Cisco and third-party firewalls, simplifying operations.', 2, true, 1),
('sec-006', 'SECURITY', 'This Cisco platform offers passwordless authentication for phishing resistance:', ARRAY['Duo IAM', 'Cisco Identity Services Engine', 'Cisco SecureX'], 0, 1, 'Includes proximity verification without clunky hardware tokens.', 'Duo IAM acts as an identity broker with passwordless options and unique proximity verification, layering phishing resistance on existing identity infrastructure.', 2, true, 1),
('sec-007', 'SECURITY', 'Which protocol does Cisco support for agent-to-enterprise connections?', ARRAY['Model Context Protocol', 'Agent to Agent', 'Master Control Program'], 0, 1, 'Named after Model Context, not Master Control from Tron.', 'Cisco supports Model Context Protocol (MCP), enabling agentic AI to securely access enterprise resources with automated discovery and delegated authorization.', 2, true, 1),
('sec-008', 'SECURITY', 'Which products secure agentic identities together?', ARRAY['Duo IAM, Secure Access, and AI Defense', 'Duo IAM, Secure Access, and Splunk', 'Duo IAM, Secure Access, and Webex'], 0, 1, 'Unified under Security Cloud Control for agentic AI security.', 'Cisco Duo IAM, Identity Intelligence, Secure Access, and AI Defense work together under Security Cloud Control to secure agentic identities.', 2, true, 1),
('sec-009', 'SECURITY', 'Which security platform provides dual data planes for low-risk upgrades?', ARRAY['Hypershield', 'Hyperfabric', 'Hyperactive'], 0, 1, 'Revolutionary security platform with dual data planes.', 'Cisco Hypershield uses dual data planes to enable zero-downtime upgrades, allowing security policy updates without service interruption or risk.', 2, true, 1),
('sec-010', 'SECURITY', 'Which security platform provides compensating controls for the patch gap?', ARRAY['Hypershield', 'Hyperconverged', 'Hypercolour'], 0, 1, 'Addresses the gap between risk discovery and patch deployment.', 'Cisco Hypershield provides compensating controls that protect vulnerabilities immediately upon discovery, before patches can be applied and tested.', 2, true, 1),
('sec-011', 'SECURITY', 'Which policy manager unifies Cisco and third-party firewalls?', ARRAY['Security Cloud Control', 'Unified Policy Manager', 'Control Tower'], 0, 1, 'It controls security from the cloud.', 'Cisco Security Cloud Control provides a unified policy manager for Cisco and third-party firewalls, enabling consistent security enforcement across hybrid environments.', 2, true, 1),
('sec-012', 'SECURITY', 'Which Cisco platform automates vulnerability discovery and remediation?', ARRAY['XDR', 'Secure Workload', 'Fix-It Felix'], 0, 1, 'Extended Detection and Response across the enterprise.', 'Cisco XDR (Extended Detection and Response) automates vulnerability discovery and remediation by correlating telemetry from network, endpoint, and cloud security tools.', 2, true, 1),
('sec-013', 'SECURITY', 'Which Cisco switches are "Hypershield-ready"?', ARRAY['Smart Switches', 'Catalyst Switches', 'Dumb Switches'], 0, 1, 'Integrate with Security Cloud Control for unified policy.', 'C9000 Smart Switches are Hypershield-ready, serving as enforcement points for unified policy management through Security Cloud Control.', 2, true, 1),
('sec-014', 'SECURITY', 'Which data center fabric integrates with Cisco Security Cloud Control?', ARRAY['ACI', 'VXLAN Fabric', 'SD-Access Fabric'], 0, 1, 'Enables unified policy management across data centers.', 'Cisco ACI data center fabrics integrate with Security Cloud Control for expanded enforcement points as part of the Hybrid Mesh Firewall strategy.', 2, true, 1),
('sec-015', 'SECURITY', 'Which switches support post-quantum cryptography?', ARRAY['Smart Switches', 'Catalyst Switches', 'Schrödinger Switches'], 0, 1, 'Protection against future quantum decryption attacks.', 'Cisco Smart Switches include post-quantum cryptography to protect against the threat of quantum computers breaking current encryption standards.', 2, true, 1),
('sec-016', 'SECURITY', 'Which switches embed DPUs in each switchport for line-rate firewalling?', ARRAY['Smart Switches', 'Meraki Switches', 'Paranoid Switches'], 0, 1, 'Line-rate firewalling in every single port.', 'Cisco Smart Switches embed Data Processing Units (DPUs) in each switchport, enabling line-rate firewall inspection on every port without performance degradation.', 2, true, 1),
('sec-017', 'SECURITY', 'Name Cisco''s platform with dual data planes for low-risk upgrades:', ARRAY['Hypershield', 'Hyperfabric', 'Hyperactive'], 0, 1, 'Revolutionary security platform with dual data planes.', 'Cisco Hypershield uses dual data planes to enable zero-downtime upgrades, allowing security policy updates without service interruption or risk.', 2, true, 1),
('sec-018', 'SECURITY', 'Name Cisco''s platform with compensating controls for the patch gap:', ARRAY['Hypershield', 'Hyperconverged', 'Hypercolour'], 0, 1, 'Addresses the gap between risk discovery and patch deployment.', 'Cisco Hypershield provides compensating controls that protect vulnerabilities immediately upon discovery, before patches can be applied and tested.', 2, true, 1);

-- ============================================================================
-- COLLABORATION CATEGORY (18 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, correct_index, drop_index, hint_9s, explanation, difficulty, active, version) VALUES
('col-001', 'COLLABORATION', 'How many specialized AI Agents were introduced for Webex Suite at WebexOne 2025?', ARRAY['5', '7', '42'], 0, 1, 'You can count them on one hand.', 'Cisco introduced 10 specialized AI Agents for Webex Suite at WebexOne 2025, covering various collaboration scenarios from meeting assistance to workflow automation.', 2, true, 1),
('col-002', 'COLLABORATION', 'What is Cisco''s cloud-connected operating system for collaboration devices?', ARRAY['RoomOS', 'WebexOS', 'SOS'], 0, 1, 'Think about where these devices typically live.', 'RoomOS is Cisco''s cloud-connected operating system that powers Webex devices, providing intelligent features, security updates, and AI-powered capabilities.', 2, true, 1),
('col-003', 'COLLABORATION', 'Which Apple device now supports sharing and manipulating 3D models in Webex meetings?', ARRAY['Vision Pro', 'iPad Pro', 'iPod'], 0, 1, 'It''s Apple''s newest spatial computing device.', 'Apple Vision Pro now supports sharing and manipulating 3D models in Webex meetings, enabling immersive spatial collaboration experiences.', 2, true, 1),
('col-004', 'COLLABORATION', 'What AI-powered tool in Control Hub delivers analytics insights to IT teams?', ARRAY['Webex AI Assistant', 'Analytics Engine', 'Crystal Ball Pro'], 0, 1, 'It''s an AI helper specifically for Webex.', 'Webex AI Assistant in Control Hub provides IT teams with intelligent analytics insights, helping them proactively manage collaboration environments and optimize user experiences.', 2, true, 1),
('col-005', 'COLLABORATION', 'What feature allows Webex meetings to continue even during internet disruptions or outages?', ARRAY['Webex Go', 'Meeting Continuity', 'Carrier Pigeon Mode'], 0, 1, 'The name suggests mobility and keeping things moving.', 'Webex Go allows meetings to continue seamlessly even during internet disruptions by automatically switching to cellular or alternative connections, ensuring uninterrupted collaboration.', 2, true, 1),
('col-006', 'COLLABORATION', 'Which Webex Contact Center AI feature detects agent burnout in real time?', ARRAY['Agent Wellbeing', 'Performance Monitor', 'Stress-o-Meter'], 0, 1, 'It focuses on the health and wellness of agents.', 'Agent Wellbeing uses AI to detect signs of agent burnout in real time by analyzing interaction patterns, sentiment, and workload, helping supervisors intervene proactively.', 2, true, 1),
('col-007', 'COLLABORATION', 'What does MCP stand for in the context of Webex AI Agent capabilities?', ARRAY['Model Context Protocol', 'Multi-Channel Processing', 'Master Control Program'], 0, 1, 'It''s about providing context to AI models.', 'Model Context Protocol (MCP) enables Webex AI Agents to securely access enterprise data and systems with proper context, allowing them to perform tasks on behalf of users.', 2, true, 1),
('col-008', 'COLLABORATION', 'What new Cisco Desk Phone series was announced at WebexOne 2025?', ARRAY['9900 Series', '8900 Series', '911 Series'], 0, 1, 'It''s in the high 9000s range.', 'The Cisco Desk Phone 9900 Series was announced at WebexOne 2025, featuring advanced AI capabilities, superior audio quality, and seamless Webex integration.', 2, true, 1),
('col-009', 'COLLABORATION', 'Which messaging platforms are supported as digital channels in Contact Center Enterprise?', ARRAY['WhatsApp, Facebook Messenger, SMS', 'Telegram, WeChat, iMessage', 'Tinder, Bumble, eHarmony, Hinge'], 0, 1, 'Think of the most popular global messaging platforms.', 'Webex Contact Center Enterprise supports WhatsApp, Facebook Messenger, and SMS as digital channels, enabling customers to engage through their preferred messaging platforms.', 2, true, 1),
('col-010', 'COLLABORATION', 'What Webex AI feature auto-generates action items from meeting summaries?', ARRAY['AI Actions', 'Smart Tasks', 'Nag Bot'], 0, 1, 'The name directly describes what it does with AI.', 'AI Actions automatically generates action items from meeting summaries and offers options to complete tasks directly within Webex, improving productivity and follow-through.', 2, true, 1),
('col-011', 'COLLABORATION', 'What quality management solution auto-scores interactions and provides coaching?', ARRAY['Webex Workforce Optimization', 'Performance Improvement Protocol', 'The Judge'], 0, 1, 'It optimizes your entire workforce, not just quality.', 'Webex Workforce Optimization automatically scores customer interactions using AI, provides coaching recommendations, and helps supervisors improve agent performance across all channels.', 2, true, 1),
('col-012', 'COLLABORATION', 'What intelligent feature on RoomOS automatically predicts meeting flow and adapts the camera mode?', ARRAY['Intelligent Director', 'Smart Framing', 'Psychic Mode'], 0, 1, 'It directs the meeting like a film director.', 'Intelligent Director uses AI to predict meeting flow and automatically adapts camera modes, ensuring the right people are framed at the right time for more natural collaboration.', 2, true, 1),
('col-013', 'COLLABORATION', 'What analytics feature transcribes and summarizes calls to identify interaction patterns?', ARRAY['Conversation Intelligence', 'Call Analytics', 'Eavesdropper Pro'], 0, 1, 'It makes conversations intelligent through analysis.', 'Conversation Intelligence transcribes and summarizes customer calls, identifying common interaction drivers, sentiment trends, and coaching opportunities to improve contact center performance.', 2, true, 1),
('col-014', 'COLLABORATION', 'What Webex Meetings feature uses AI to remove background noise in real time?', ARRAY['Noise Removal', 'Audio Enhancement', 'Dog Shoosher'], 0, 1, 'It literally removes the noise.', 'Noise Removal uses AI to intelligently filter out background sounds like keyboard typing, barking dogs, and construction noise in real time, ensuring crystal-clear audio in meetings.', 2, true, 1),
('col-015', 'COLLABORATION', 'Which Cisco device family includes the Desk, Board, and Room series?', ARRAY['Cisco Collaboration Devices', 'Webex Endpoints', 'Meeting Magic Series'], 0, 1, 'They all work together for collaboration.', 'Cisco Collaboration Devices is the portfolio that includes Webex Desk devices, Board devices, and Room systems, all powered by RoomOS for intelligent collaboration experiences.', 2, true, 1),
('col-016', 'COLLABORATION', 'What feature allows participants to join Webex meetings directly from Microsoft Teams?', ARRAY['Webex for Microsoft Teams', 'Cross-Platform Join', 'Endless Meetings Pro'], 0, 1, 'It''s Webex embedded in Microsoft Teams.', 'Webex for Microsoft Teams allows users to join Webex meetings directly from within Microsoft Teams without switching applications, enabling seamless cross-platform collaboration.', 2, true, 1),
('col-017', 'COLLABORATION', 'What is the maximum number of participants supported in a Webex Webinar?', ARRAY['100,000', '10,000', '1,000'], 0, 1, 'It''s a six-figure number.', 'Webex Webinars support up to 100,000 participants, making it ideal for large-scale virtual events, town halls, and broadcasts with interactive Q&A and engagement features.', 2, true, 1),
('col-018', 'COLLABORATION', 'Which Webex feature provides real-time translation and closed captioning during meetings?', ARRAY['Real-Time Translation', 'Live Captions', 'Babel Fish Mode'], 0, 1, 'The feature name tells you exactly what it does.', 'Real-Time Translation provides live translation and closed captioning in over 100 languages during Webex meetings, breaking down language barriers and improving accessibility for global teams.', 2, true, 1);

-- ============================================================================
-- DATA_CENTER CATEGORY (20 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, correct_index, drop_index, hint_9s, explanation, difficulty, active, version) VALUES
('dc-001', 'DATA_CENTER', 'Which Cisco storage solution supports Ethernet, Fibre Channel, and NVMe over Fabrics?', ARRAY['MDS 9000 Series', 'Nexus 9000 Series', 'Magic Data Storage'], 0, 1, 'It''s the Multi-layer Director Switch family.', 'The MDS 9000 Series is Cisco''s storage networking platform that supports Ethernet, Fibre Channel, and NVMe over Fabrics, providing flexible connectivity for modern storage architectures.', 2, true, 1),
('dc-002', 'DATA_CENTER', 'What is the name of Cisco''s intent-based network for data center automation?', ARRAY['ACI (Application Centric Infrastructure)', 'DNA Center', 'Skynet'], 0, 1, 'It puts Applications at the Centre of everything.', 'ACI (Application Centric Infrastructure) is Cisco''s software-defined networking solution for data centers, automating network provisioning and policy enforcement based on application requirements.', 2, true, 1),
('dc-003', 'DATA_CENTER', 'Which Cisco platform provides unified management for compute, storage, and network resources?', ARRAY['Intersight', 'UCS Manager', 'Control Freak Central'], 0, 1, 'It gives you insight across your infrastructure.', 'Cisco Intersight is a cloud-based management platform that provides unified visibility and control over compute, storage, and network resources across on-premises and cloud environments.', 2, true, 1),
('dc-004', 'DATA_CENTER', 'What modular server platform supports multiple form factors in a single chassis?', ARRAY['UCS X-Series', 'UCS C-Series', 'UCS Why-Series'], 0, 1, 'It''s the newest X-factor in UCS.', 'UCS X-Series is Cisco''s modular compute platform that supports multiple form factors (blade and rack) in a single chassis, providing flexibility and investment protection for data centers.', 2, true, 1),
('dc-005', 'DATA_CENTER', 'Which Cisco technology enables lossless Ethernet for storage networks?', ARRAY['Data Center Bridging', 'Quality of Service', 'No Packet Left Behind'], 0, 1, 'It bridges the gap between Ethernet and storage.', 'Data Center Bridging (DCB) enables lossless Ethernet by implementing Priority Flow Control and Enhanced Transmission Selection, making Ethernet suitable for converged storage networks.', 2, true, 1),
('dc-006', 'DATA_CENTER', 'What is Cisco''s hyperconverged infrastructure solution?', ARRAY['HyperFlex', 'HyperScale', 'HyperActive'], 0, 1, 'It makes infrastructure hyper-flexible.', 'Cisco HyperFlex is a hyperconverged infrastructure solution that combines compute, storage, and networking with software-defined management, simplifying data center operations and reducing complexity.', 2, true, 1),
('dc-007', 'DATA_CENTER', 'Which GPU vendor does Cisco partner with for AI infrastructure?', ARRAY['NVIDIA', 'AMD', 'Intel'], 0, 1, 'The leader in AI and GPU computing.', 'Cisco partners with NVIDIA to deliver AI infrastructure solutions, integrating NVIDIA GPUs and DPUs with Cisco UCS servers and networking for optimized AI and machine learning workloads.', 2, true, 1),
('dc-008', 'DATA_CENTER', 'What networking technology does ACI use for its fabric?', ARRAY['VXLAN', 'MPLS', 'String and Tin Cans'], 0, 1, 'Virtual eXtensible LAN technology.', 'ACI uses VXLAN (Virtual Extensible LAN) for its fabric overlay, enabling network segmentation and multi-tenancy while providing Layer 2 connectivity over a Layer 3 underlay.', 2, true, 1),
('dc-009', 'DATA_CENTER', 'Which protocol does Cisco use for automated switch fabric configuration?', ARRAY['VXLAN BGP EVPN', 'OSPF', 'Carrier Pigeons'], 0, 1, 'It''s VXLAN with BGP for control plane.', 'VXLAN BGP EVPN (Ethernet VPN) is used in Cisco fabrics to automate switch configuration, provide MAC and IP learning, and enable seamless Layer 2 and Layer 3 connectivity across the data center.', 2, true, 1),
('dc-010', 'DATA_CENTER', 'What Cisco server series is optimized for GPU-intensive AI workloads?', ARRAY['UCS C-Series', 'UCS B-Series', 'UCS AI-Series'], 0, 1, 'It''s the rack-mount C Series.', 'The UCS C-Series rack servers are optimized for GPU-intensive AI workloads, supporting multiple high-performance GPUs with PCIe connectivity and high-bandwidth networking for distributed training.', 2, true, 1),
('dc-011', 'DATA_CENTER', 'Which Cisco storage networking switch supports 64Gbps Fibre Channel?', ARRAY['MDS 9700 Series', 'MDS 9500 Series', 'MDS Light Speed'], 0, 1, 'It''s the highest number in the MDS family.', 'The MDS 9700 Series supports 64 Gigabit Fibre Channel, providing ultra-high-speed storage connectivity for demanding enterprise and cloud data center storage area networks.', 2, true, 1),
('dc-012', 'DATA_CENTER', 'What is the maximum number of UCS blade servers supported in a single chassis?', ARRAY['8', '16', '42'], 0, 1, 'It''s a single-digit number you can count easily.', 'A single UCS 5100 Series blade chassis supports up to 8 half-width or 4 full-width blade servers, providing high-density compute in a compact form factor.', 2, true, 1),
('dc-013', 'DATA_CENTER', 'Which open-source container orchestration platform does Cisco support?', ARRAY['Kubernetes', 'Docker Swarm', 'Herd of Cats'], 0, 1, 'It''s the industry-standard container orchestrator.', 'Cisco supports Kubernetes extensively across its portfolio, including integration with ACI, HyperFlex, and Intersight for container networking, storage, and management.', 2, true, 1),
('dc-014', 'DATA_CENTER', 'What Cisco technology provides multi-cloud connectivity and policy enforcement?', ARRAY['Multi-Cloud Defense', 'Cloud ACI', 'Cloud Glue'], 0, 1, 'It defends across multiple clouds.', 'Cisco Multi-Cloud Defense provides consistent connectivity and security policy enforcement across AWS, Azure, Google Cloud, and on-premises environments from a single control plane.', 2, true, 1),
('dc-015', 'DATA_CENTER', 'Which Nexus switch series is designed specifically for leaf-spine architectures?', ARRAY['Nexus 9000 Series', 'Nexus 7000 Series', 'Nexus Leaf Blower'], 0, 1, 'It''s the 9000 family built for modern fabrics.', 'The Nexus 9000 Series is purpose-built for leaf-spine data center architectures, offering ultra-low latency, high bandwidth, and support for both ACI and traditional NX-OS deployments.', 2, true, 1),
('dc-016', 'DATA_CENTER', 'What type of memory technology does UCS X-Series support for high-performance workloads?', ARRAY['DDR5', 'DDR4', 'USB Stick'], 0, 1, 'It''s the latest generation of DDR memory.', 'UCS X-Series supports DDR5 memory technology, providing significantly higher bandwidth and lower power consumption compared to DDR4 for demanding enterprise and AI applications.', 2, true, 1),
('dc-017', 'DATA_CENTER', 'Which Cisco platform enables Infrastructure as Code for UCS deployments?', ARRAY['Intersight Terraform Provider', 'UCS PowerTool', 'Code Wizard'], 0, 1, 'It uses the popular IaC tool Terraform.', 'The Intersight Terraform Provider enables Infrastructure as Code for UCS deployments, allowing automated, repeatable, and version-controlled infrastructure provisioning through Terraform.', 2, true, 1),
('dc-018', 'DATA_CENTER', 'What networking speed do the latest Nexus switches support for AI cluster connectivity?', ARRAY['800 Gbps', '400 Gbps', '56K modem'], 0, 1, 'It''s double the already-fast 400G.', 'The latest Nexus switches support 800 Gigabit Ethernet for AI cluster connectivity, providing the massive bandwidth required for GPU-to-GPU communication in distributed AI training.', 2, true, 1),
('dc-019', 'DATA_CENTER', 'Which power management feature automatically optimizes UCS server power consumption?', ARRAY['Power Capping', 'Eco Mode', 'Lights Out'], 0, 1, 'It puts a cap on power usage.', 'Power Capping in UCS allows administrators to set maximum power consumption limits per server or group, ensuring data center power budgets are maintained while optimizing performance.', 2, true, 1),
('dc-020', 'DATA_CENTER', 'What Cisco technology provides workload optimization across on-premises and cloud?', ARRAY['Intersight Workload Optimizer', 'CloudCenter', 'Magic 8-Ball'], 0, 1, 'Intersight helps optimize your workloads.', 'Intersight Workload Optimizer uses AI to continuously analyze application performance and automatically recommend or execute resource adjustments across hybrid cloud environments for optimal efficiency.', 2, true, 1);

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================
-- Run this query after migration to verify all categories and counts

SELECT 
    category,
    COUNT(*) as question_count,
    COUNT(CASE WHEN active = true THEN 1 END) as active_count
FROM trivia_items
GROUP BY category
ORDER BY category;

-- Expected results:
-- NETWORKING: 25 questions (25 active)
-- SECURITY: 18 questions (18 active)
-- COLLABORATION: 18 questions (18 active)
-- DATA_CENTER: 20 questions (20 active)
-- TOTAL: 81 questions (81 active)
