-- ============================================================================
-- DATA#3 CISCO LIVE - TRIVIA MIGRATION TO 4 CATEGORIES
-- ============================================================================
-- This SQL file migrates from 5 categories to 4 new categories with updated
-- trivia questions.
--
-- New Categories:
--   1. NETWORKING (25 questions)
--   2. SECURITY (18 questions)
--   3. COLLABORATION (18 questions)
--   4. DATA_CENTER (20 questions)
--
-- Total: 81 trivia questions
--
-- Table: trivia_items
-- Columns: id, category, stem, choices (array), correctIndex, dropIndex,
--          hint_9s, explanation, active, version
-- ============================================================================

-- Step 1: Clear existing trivia questions
DELETE FROM trivia_items;

-- ============================================================================
-- NETWORKING CATEGORY (25 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, "correctIndex", "dropIndex", hint_9s, explanation, active, version) VALUES
('net-001', 'NETWORKING', 'Which two Catalyst switch models include dedicated data processing units?', ARRAY['9400X and 9500X', '9300 and 9200', '9000 and Over 9000'], 0, 1, 'Think X marks the spot for extreme performance.', 'The Catalyst 9400X and 9500X include dedicated DPUs (Data Processing Units) that enable advanced security and analytics at the switching layer without impacting forwarding performance.', true, 1),
('net-002', 'NETWORKING', 'Which Nexus switch series includes models with DPUs for AI workloads?', ARRAY['Nexus 9300', 'Nexus 7000', 'Nexus 42'], 0, 1, 'It''s in the 9000 family, but lower than 9500.', 'The Nexus 9300 series includes models with dedicated DPUs designed to accelerate AI workloads, provide inline security, and handle telemetry processing without affecting network throughput.', true, 1),
('net-003', 'NETWORKING', 'What network speed optics did Cisco announce for AI-ready data centers?', ARRAY['800G', '400G', '88 MPH'], 0, 1, 'Double what you think is already really fast.', 'Cisco announced 800 Gigabit Ethernet optics for AI-ready data centers, supporting the massive bandwidth requirements of GPU-to-GPU communication in AI training clusters.', true, 1),
('net-004', 'NETWORKING', 'What is Cisco''s new switch series designed for AI data centers with NVIDIA GPU integration?', ARRAY['Nexus HyperFabric', 'Catalyst AI', 'Cisco SkyNet'], 0, 1, 'It''s Hyper-focused on fabric connectivity.', 'Nexus HyperFabric is Cisco''s purpose-built switching platform for AI data centers, featuring deep integration with NVIDIA GPUs and optimized for ultra-low latency AI workloads.', true, 1),
('net-005', 'NETWORKING', 'Which fabrics does the Unified Nexus Dashboard consolidate?', ARRAY['ACI, VXLAN, and traditional networks', 'Campus, WAN, and Data Center', 'Cotton, Silk, and Polyester'], 0, 1, 'Think about the underlying network protocols, not locations.', 'The Unified Nexus Dashboard consolidates management of ACI (Application Centric Infrastructure), VXLAN-based networks, and traditional switching fabrics into a single interface.', true, 1),
('net-006', 'NETWORKING', 'What security capability do Smart Switches deliver at line rate?', ARRAY['DPU-based firewalling', 'AI threat detection', 'Enterprise Trust Issues'], 0, 1, 'It uses those special processing units we keep mentioning.', 'Smart Switches use embedded DPUs to deliver line-rate firewall inspection on every port without performance degradation, extending zero-trust security to the switching layer.', true, 1),
('net-007', 'NETWORKING', 'Which Cisco technology provides AI-driven security enforcement across distributed networks?', ARRAY['Hypershield', 'Hyperfabric', 'Hypercolour'], 0, 1, 'It''s hyper-focused on distributed security.', 'Cisco Hypershield provides AI-driven security enforcement across distributed networks using dual data planes and compensating controls to protect against threats at massive scale.', true, 1),
('net-008', 'NETWORKING', 'What Cisco platform combines routing, SD-WAN, and firewall in a single appliance?', ARRAY['Cisco 8000 Secure Router', 'ISR 4000 Series', 'Swiss Army Router'], 0, 1, 'It''s in the 8000 family and it''s Secure.', 'The Cisco 8000 Secure Router series combines high-performance routing, SD-WAN capabilities, and next-generation firewall functions in a single platform for simplified branch deployments.', true, 1),
('net-009', 'NETWORKING', 'What is Cisco''s AI-based collaborative workspace for advanced troubleshooting?', ARRAY['AI Canvas', 'Webex AI Assistant', 'Clippy 2.0'], 0, 1, 'It helps you see with a thousand perspectives.', 'ThousandEyes Copilot is an AI-powered collaborative workspace that helps network teams diagnose complex issues faster by providing intelligent insights and automated troubleshooting recommendations.', true, 1),
('net-010', 'NETWORKING', 'What does Cisco call its unified security strategy including Secure Firewall and Hypershield?', ARRAY['Hybrid Mesh Firewall', 'Unified Security Platform', 'Security Spaghetti Junction'], 0, 1, 'It''s a mesh that works in hybrid environments.', 'Hybrid Mesh Firewall is Cisco''s strategy to unify security enforcement across Cisco Secure Firewall, Hypershield, Meraki, ASA, and third-party firewalls under a single policy framework.', true, 1),
('net-011', 'NETWORKING', 'Which technology partnership enabled Cisco to add DPUs to switches?', ARRAY['NVIDIA', 'Intel', 'AMD'], 0, 1, 'The same company famous for GPUs also makes DPUs.', 'Cisco partnered with NVIDIA to integrate NVIDIA BlueField DPUs into switches, enabling advanced processing capabilities for security, telemetry, and AI workload acceleration.', true, 1),
('net-012', 'NETWORKING', 'What type of security does Cisco''s Secure Router series include against quantum threats?', ARRAY['Post-quantum cryptography', 'Quantum-resistant encryption', 'Schrödinger Pro'], 0, 1, 'It comes after quantum computing becomes a threat.', 'Cisco''s Secure Router series includes post-quantum cryptography algorithms designed to protect against future attacks from quantum computers that could break current encryption standards.', true, 1),
('net-013', 'NETWORKING', 'What does Cisco call its vision of using AI agents to diagnose network issues proactively?', ARRAY['Agentic AI', 'Synthetic Support Desk', 'Network Psychics United'], 0, 1, 'The agents are doing the work for you.', 'Agentic AI is Cisco''s vision where AI agents autonomously diagnose, predict, and resolve network issues before they impact users, transforming network operations.', true, 1),
('net-014', 'NETWORKING', 'What is the maximum switching capacity of the Catalyst 9000X series?', ARRAY['25.6 Tbps', '25.6 Gbps', '25.6 Mbps'], 0, 1, 'Think big. Seriously, big.', 'The Catalyst 9000X series delivers up to 25.6 Terabits per second of switching capacity, supporting high-density, high-performance enterprise and data center deployments.', true, 1),
('net-015', 'NETWORKING', 'Which Catalyst switch platform supports Universal PoE for high-power devices?', ARRAY['Catalyst 9000 Series', 'Catalyst 3850 Series', 'Catalyst Unlimited Power Edition'], 0, 1, 'It''s the current flagship 9000 family.', 'The Catalyst 9000 Series supports Universal PoE (UPoE) delivering up to 60W per port, enabling high-power devices like PTZ cameras, wireless access points, and digital displays.', true, 1),
('net-016', 'NETWORKING', 'What power budget can Cisco''s Ultra PoE switches deliver per port?', ARRAY['90W', '60W', '1.21 Gigawatts'], 0, 1, 'It''s 50% more than Universal PoE.', 'Cisco''s Ultra PoE (UPoE+) switches can deliver up to 90 watts per port, supporting the most power-hungry devices like LED lighting, building automation, and advanced PTZ cameras.', true, 1),
('net-017', 'NETWORKING', 'Which Cisco switch operating system powers both Catalyst and Nexus platforms?', ARRAY['IOS-XE', 'NX-OS', 'S-OS'], 0, 1, 'It''s the eXtended Edition of a classic.', 'Cisco IOS XE is the modern operating system powering Catalyst switches, while select Nexus platforms also support it, providing consistency across enterprise and data center environments.', true, 1),
('net-018', 'NETWORKING', 'What is the name of Cisco''s intent-based networking platform for enterprise networks?', ARRAY['Cisco Catalyst Center', 'Cisco Prime Infrastructure', 'Cisco SkyNet'], 0, 1, 'It understands the DNA of your network.', 'Cisco DNA Center is the intent-based networking platform that automates network provisioning, policy enforcement, and assurance across the enterprise using AI and machine learning.', true, 1),
('net-019', 'NETWORKING', 'Which Catalyst switch series is optimized for cloud-scale deployments?', ARRAY['Cisco Catalyst 9000 Series', 'Cisco Nexus 9000 Series', 'Cisco Nimbus 9000 Series'], 0, 1, 'The highest number in the current lineup.', 'The Catalyst 9000 Series is purpose-built for cloud-scale deployments with programmable ASICs, telemetry, automation APIs, and the performance needed for modern hybrid cloud architectures.', true, 1),
('net-020', 'NETWORKING', 'What switching technology enables lossless Ethernet for storage and AI workloads?', ARRAY['Priority Flow Control', 'Quality of Service', 'No Packet Left Behind Protocol'], 0, 1, 'It controls the flow with priority.', 'Priority Flow Control (PFC) enables lossless Ethernet by pausing transmission on congested queues, essential for storage protocols like iSCSI and AI workloads that cannot tolerate packet loss.', true, 1),
('net-021', 'NETWORKING', 'Which Nexus platform is designed specifically for spine-leaf architectures?', ARRAY['Nexus 9000 Series', 'Nexus 7000 Series', 'Nexus 5000 Series'], 0, 1, 'It''s the 9000 series built for modern fabrics.', 'The Nexus 9000 series is purpose-built for spine-leaf data center architectures, offering ultra-low latency, high bandwidth, and support for both ACI and NX-OS modes.', true, 1),
('net-022', 'NETWORKING', 'What is the total throughput capacity of the Nexus 9000 series flagship model?', ARRAY['64 Tbps', '32 Tbps', '16 Tbps'], 0, 1, 'Double what seems already unreasonably fast.', 'The Nexus 9000 series flagship models deliver up to 64 Terabits per second of throughput, supporting the most demanding hyperscale data center and AI infrastructure requirements.', true, 1),
('net-023', 'NETWORKING', 'Which Cisco switching feature provides microsecond-level network telemetry?', ARRAY['Streaming Telemetry', 'NetFlow', 'Gossip Protocol'], 0, 1, 'It streams data in real time, not in batches.', 'Streaming Telemetry provides microsecond-level visibility into network behavior by continuously pushing real-time data, unlike traditional polling methods, enabling faster anomaly detection.', true, 1),
('net-024', 'NETWORKING', 'What technology allows Cisco switches to segment networks without VLANs?', ARRAY['TrustSec', 'VRF', 'VLAN-Free Zones'], 0, 1, 'It''s about trust and security, not VLANs.', 'Cisco TrustSec uses Security Group Tags (SGTs) to segment networks based on identity rather than IP addresses or VLANs, simplifying policy enforcement and improving security.', true, 1),
('net-025', 'NETWORKING', 'Which Catalyst series includes Wi-Fi 7 integrated access points?', ARRAY['Catalyst 9130', 'Catalyst 9800', 'Catalyst 404'], 0, 1, 'It''s the access point series, not the wireless controller.', 'The Catalyst 9130 series access points support Wi-Fi 7 (802.11be), delivering multi-gigabit speeds, ultra-low latency, and support for dense, high-performance wireless environments.', true, 1);

-- ============================================================================
-- SECURITY CATEGORY (18 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, "correctIndex", "dropIndex", hint_9s, explanation, active, version) VALUES
('sec-001', 'SECURITY', 'This framework includes distributed firewalls and Hypershield:', ARRAY['Hybrid Mesh Firewall', 'Hybrid Cloud Defense Matrix', 'Firewall Farm Federation'], 0, 1, 'This portfolio adds enforcement points across diverse environments.', 'Cisco''s Hybrid Mesh Firewall is a distributed security fabric that includes Cisco and third-party firewalls, Cisco Hypershield, and Cisco Secure Workload for zero-trust segmentation.', true, 1),
('sec-002', 'SECURITY', 'What does ZTNA stand for?', ARRAY['Zero Trust Network Access', 'Zero Threat Network Architecture', 'Zombies That Never Attack'], 0, 1, 'Ensures identity-driven access for users, devices, and AI agents.', 'Universal ZTNA stands for Universal Zero Trust Network Access, ensuring seamless, identity-driven access while simplifying secure connectivity across hybrid environments.', true, 1),
('sec-003', 'SECURITY', 'What is the per-RU performance density of the Cisco Secure Firewall 6100?', ARRAY['200 Gbps', '20 Gbps', '2 Gbps'], 0, 1, 'The biggest number is usually correct!', 'The Cisco Secure Firewall 6100 Series delivers 200 Gbps per rack unit, providing the highest performance density for data center firewalling.', true, 1),
('sec-004', 'SECURITY', 'Which branch firewall series has integrated SD-WAN?', ARRAY['200 Series', '8000 Series', '404 Series'], 0, 1, 'Delivers up to 3x price-performance compared to competition.', 'The Cisco Secure Firewall 200 Series is designed for distributed branches with integrated SD-WAN at up to 3x price-performance compared to competition.', true, 1),
('sec-005', 'SECURITY', 'Name the Cisco Security Cloud Control unified policy engine:', ARRAY['Mesh Policy Engine', 'Identity Service Engine', 'Internal Combustion Engine'], 0, 1, 'Everything connects to everything.', 'The Mesh Policy Engine enables teams to define a single intent-based policy enforced across Cisco and third-party firewalls, simplifying operations.', true, 1),
('sec-006', 'SECURITY', 'This Cisco platform offers passwordless authentication for phishing resistance:', ARRAY['Duo IAM', 'Cisco Identity Services Engine', 'Cisco SecureX'], 0, 1, 'Includes proximity verification without clunky hardware tokens.', 'Duo IAM acts as an identity broker with passwordless options and unique proximity verification, layering phishing resistance on existing identity infrastructure.', true, 1),
('sec-007', 'SECURITY', 'Which protocol does Cisco support for agent-to-enterprise connections?', ARRAY['Model Context Protocol', 'Agent to Agent', 'Master Control Program'], 0, 1, 'Named after Model Context, not Master Control from Tron.', 'Cisco supports Model Context Protocol (MCP), enabling agentic AI to securely access enterprise resources with automated discovery and delegated authorization.', true, 1),
('sec-008', 'SECURITY', 'Which products secure agentic identities together?', ARRAY['Duo IAM, Secure Access, and AI Defense', 'Duo IAM, Secure Access, and Splunk', 'Duo IAM, Secure Access, and Webex'], 0, 1, 'Unified under Security Cloud Control for agentic AI security.', 'Cisco Duo IAM, Identity Intelligence, Secure Access, and AI Defense work together under Security Cloud Control to secure agentic identities.', true, 1),
('sec-009', 'SECURITY', 'What edge security service integrates with all SD-WAN offerings, including Meraki?', ARRAY['SASE', 'SASI', 'SASSY'], 0, 1, 'The definition keeps shifting, but edge security is critical.', 'SASE is simplified through integration of all Cisco SD-WAN offerings with Cisco Secure Access, enabling optimal branch connectivity with unified SSE policy.', true, 1),
('sec-010', 'SECURITY', 'Which router series supports NGFW via Security Cloud Control?', ARRAY['8000 Series', '3800 Series', '800 Series'], 0, 1, 'Part of Cisco Catalyst SD-WAN with expanded enforcement.', 'The Cisco 8000 Secure Router Series supports next-generation firewall capabilities on Catalyst SD-WAN through unified policy management.', true, 1),
('sec-011', 'SECURITY', 'Name the acquisition that became the foundation of Cisco Data Fabric:', ARRAY['Splunk', 'Thousand Eyes', 'Snort'], 0, 1, 'If you can imagine it, you can build it in SPL.', 'The Cisco Security Cloud App for Splunk delivers deeper support for Cisco Secure Firewall Threat Defense, enabling enriched correlation and detection.', true, 1),
('sec-012', 'SECURITY', 'Cisco Splunk accelerates which security workflow?', ARRAY['Traffic Diagnosis, Inspection, and Response', 'Traffic Diagnosis, Inspection, and Recovery', 'Total Destruction after Incident Replay'], 0, 1, 'Enhanced through deeper Cisco Secure Firewall integration.', 'TDIR stands for Threat Detection, Investigation and Response - comprehensive security workflows enhanced through Cisco and Splunk integrations.', true, 1),
('sec-013', 'SECURITY', 'Which Cisco switches are "Hypershield-ready"?', ARRAY['Smart Switches', 'Catalyst Switches', 'Dumb Switches'], 0, 1, 'Integrate with Security Cloud Control for unified policy.', 'C9000 Smart Switches are Hypershield-ready, serving as enforcement points for unified policy management through Security Cloud Control.', true, 1),
('sec-014', 'SECURITY', 'Which data center fabric integrates with Cisco Security Cloud Control?', ARRAY['ACI', 'VXLAN Fabric', 'SD-Access Fabric'], 0, 1, 'Enables unified policy management across data centers.', 'Cisco ACI data center fabrics integrate with Security Cloud Control for expanded enforcement points as part of the Hybrid Mesh Firewall strategy.', true, 1),
('sec-015', 'SECURITY', 'Which switches support post-quantum cryptography?', ARRAY['Smart Switches', 'Catalyst Switches', 'Schrödinger Switches'], 0, 1, 'Protection against future quantum decryption attacks.', 'Cisco Smart Switches include post-quantum cryptography to protect against the threat of quantum computers breaking current encryption standards.', true, 1),
('sec-016', 'SECURITY', 'Which switches embed DPUs in each switchport for line-rate firewalling?', ARRAY['Smart Switches', 'Meraki Switches', 'Paranoid Switches'], 0, 1, 'Line-rate firewalling in every single port.', 'Cisco Smart Switches embed Data Processing Units (DPUs) in each switchport, enabling line-rate firewall inspection on every port without performance degradation.', true, 1),
('sec-017', 'SECURITY', 'Name Cisco''s platform with dual data planes for low-risk upgrades:', ARRAY['Hypershield', 'Hyperfabric', 'Hyperactive'], 0, 1, 'Revolutionary security platform with dual data planes.', 'Cisco Hypershield uses dual data planes to enable zero-downtime upgrades, allowing security policy updates without service interruption or risk.', true, 1),
('sec-018', 'SECURITY', 'Name Cisco''s platform with compensating controls for the patch gap:', ARRAY['Hypershield', 'Hyperconverged', 'Hypercolour'], 0, 1, 'Addresses the gap between risk discovery and patch deployment.', 'Cisco Hypershield provides compensating controls that protect vulnerabilities immediately upon discovery, before patches can be applied and tested.', true, 1);

-- ============================================================================
-- COLLABORATION CATEGORY (18 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, "correctIndex", "dropIndex", hint_9s, explanation, active, version) VALUES
('col-001', 'COLLABORATION', 'How many specialized AI Agents were introduced for Webex Suite at WebexOne 2025?', ARRAY['5', '7', '42'], 0, 1, 'You can count them on one hand.', 'Cisco introduced 10 specialized AI Agents for Webex Suite at WebexOne 2025, covering various collaboration scenarios from meeting assistance to workflow automation.', true, 1),
('col-002', 'COLLABORATION', 'What is Cisco''s cloud-connected operating system for collaboration devices?', ARRAY['RoomOS', 'WebexOS', 'SOS'], 0, 1, 'Think about where these devices typically live.', 'RoomOS is Cisco''s cloud-connected operating system that powers Webex devices, providing intelligent features, security updates, and AI-powered capabilities.', true, 1),
('col-003', 'COLLABORATION', 'Which Apple device now supports sharing and manipulating 3D models in Webex meetings?', ARRAY['Vision Pro', 'iPad Pro', 'iPod'], 0, 1, 'It''s Apple''s newest spatial computing device.', 'Apple Vision Pro now supports sharing and manipulating 3D models in Webex meetings, enabling immersive spatial collaboration experiences.', true, 1),
('col-004', 'COLLABORATION', 'What AI-powered tool in Control Hub delivers analytics insights to IT teams?', ARRAY['Webex AI Assistant', 'Analytics Engine', 'Crystal Ball Pro'], 0, 1, 'It''s an AI helper specifically for Webex.', 'Webex AI Assistant in Control Hub provides IT teams with intelligent analytics insights, helping them proactively manage collaboration environments and optimize user experiences.', true, 1),
('col-005', 'COLLABORATION', 'What feature allows Webex meetings to continue even during internet disruptions or outages?', ARRAY['Webex Go', 'Meeting Continuity', 'Carrier Pigeon Mode'], 0, 1, 'The name suggests mobility and keeping things moving.', 'Webex Go allows meetings to continue seamlessly even during internet disruptions by automatically switching to cellular or alternative connections, ensuring uninterrupted collaboration.', true, 1),
('col-006', 'COLLABORATION', 'Which Webex Contact Center AI feature detects agent burnout in real time?', ARRAY['Agent Wellbeing', 'Performance Monitor', 'Stress-o-Meter'], 0, 1, 'It focuses on the health and wellness of agents.', 'Agent Wellbeing uses AI to detect signs of agent burnout in real time by analyzing interaction patterns, sentiment, and workload, helping supervisors intervene proactively.', true, 1),
('col-007', 'COLLABORATION', 'What does MCP stand for in the context of Webex AI Agent capabilities?', ARRAY['Model Context Protocol', 'Multi-Channel Processing', 'Master Control Program'], 0, 1, 'It''s about providing context to AI models.', 'Model Context Protocol (MCP) enables Webex AI Agents to securely access enterprise data and systems with proper context, allowing them to perform tasks on behalf of users.', true, 1),
('col-008', 'COLLABORATION', 'What new Cisco Desk Phone series was announced at WebexOne 2025?', ARRAY['9900 Series', '8900 Series', '911 Series'], 0, 1, 'It''s in the high 9000s range.', 'The Cisco Desk Phone 9900 Series was announced at WebexOne 2025, featuring advanced AI capabilities, superior audio quality, and seamless Webex integration.', true, 1),
('col-009', 'COLLABORATION', 'Which messaging platforms are supported as digital channels in Contact Center Enterprise?', ARRAY['WhatsApp, Facebook Messenger, SMS', 'Telegram, WeChat, iMessage', 'Tinder, Bumble, eHarmony, Hinge'], 0, 1, 'Think of the most popular global messaging platforms.', 'Webex Contact Center Enterprise supports WhatsApp, Facebook Messenger, and SMS as digital channels, enabling customers to engage through their preferred messaging platforms.', true, 1),
('col-010', 'COLLABORATION', 'What Webex AI feature auto-generates action items from meeting summaries?', ARRAY['AI Actions', 'Smart Tasks', 'Nag Bot'], 0, 1, 'The name directly describes what it does with AI.', 'AI Actions automatically generates action items from meeting summaries and offers options to complete tasks directly within Webex, improving productivity and follow-through.', true, 1),
('col-011', 'COLLABORATION', 'What quality management solution auto-scores interactions and provides coaching?', ARRAY['Webex Workforce Optimization', 'Performance Improvement Protocol', 'The Judge'], 0, 1, 'It optimizes your entire workforce, not just quality.', 'Webex Workforce Optimization automatically scores customer interactions using AI, provides coaching recommendations, and helps supervisors improve agent performance across all channels.', true, 1),
('col-012', 'COLLABORATION', 'What intelligent feature on RoomOS automatically predicts meeting flow and adapts the camera mode?', ARRAY['Intelligent Director', 'Smart Framing', 'Psychic Mode'], 0, 1, 'It directs the meeting like a film director.', 'Intelligent Director uses AI to predict meeting flow and automatically adapts camera modes, ensuring the right people are framed at the right time for more natural collaboration.', true, 1),
('col-013', 'COLLABORATION', 'What analytics feature transcribes and summarizes calls to identify interaction patterns?', ARRAY['Conversation Intelligence', 'Call Analytics', 'Eavesdropper Pro'], 0, 1, 'It makes conversations intelligent through analysis.', 'Conversation Intelligence transcribes and summarizes customer calls, identifying common interaction drivers, sentiment trends, and coaching opportunities to improve contact center performance.', true, 1),
('col-014', 'COLLABORATION', 'What Webex Meetings feature uses AI to remove background noise in real time?', ARRAY['Noise Removal', 'Audio Enhancement', 'Dog Shoosher'], 0, 1, 'It literally removes the noise.', 'Noise Removal uses AI to intelligently filter out background sounds like keyboard typing, barking dogs, and construction noise in real time, ensuring crystal-clear audio in meetings.', true, 1),
('col-015', 'COLLABORATION', 'Which Cisco device family includes the Desk, Board, and Room series?', ARRAY['Cisco Collaboration Devices', 'Webex Endpoints', 'Meeting Magic Series'], 0, 1, 'They all work together for collaboration.', 'Cisco Collaboration Devices is the portfolio that includes Webex Desk devices, Board devices, and Room systems, all powered by RoomOS for intelligent collaboration experiences.', true, 1),
('col-016', 'COLLABORATION', 'What feature allows participants to join Webex meetings directly from Microsoft Teams?', ARRAY['Webex for Microsoft Teams', 'Cross-Platform Join', 'Endless Meetings Pro'], 0, 1, 'It''s Webex embedded in Microsoft Teams.', 'Webex for Microsoft Teams allows users to join Webex meetings directly from within Microsoft Teams without switching applications, enabling seamless cross-platform collaboration.', true, 1),
('col-017', 'COLLABORATION', 'What is the maximum number of participants supported in a Webex Webinar?', ARRAY['100,000', '10,000', '1,000'], 0, 1, 'It''s a six-figure number.', 'Webex Webinars support up to 100,000 participants, making it ideal for large-scale virtual events, town halls, and broadcasts with interactive Q&A and engagement features.', true, 1),
('col-018', 'COLLABORATION', 'Which Webex feature provides real-time translation and closed captioning during meetings?', ARRAY['Real-Time Translation', 'Live Captions', 'Babel Fish Mode'], 0, 1, 'The feature name tells you exactly what it does.', 'Real-Time Translation provides live translation and closed captioning in over 100 languages during Webex meetings, breaking down language barriers and improving accessibility for global teams.', true, 1);

-- ============================================================================
-- DATA CENTER (CLOUD & AI) CATEGORY (20 questions)
-- ============================================================================

INSERT INTO trivia_items (id, category, stem, choices, "correctIndex", "dropIndex", hint_9s, explanation, active, version) VALUES
('dc-001', 'DATA_CENTER', 'What does ACI stand for in Cisco data center networking?', ARRAY['Application Centric Infrastructure', 'Automated Cloud Infrastructure', 'All Cables Included'], 0, 1, 'It puts applications at the center of everything.', 'ACI stands for Application Centric Infrastructure, Cisco''s software-defined networking solution that automates data center fabric deployment and management based on application requirements.', true, 1),
('dc-002', 'DATA_CENTER', 'What does UCS stand for in Cisco''s compute platform?', ARRAY['Unified Computing System', 'Universal Cloud Server', 'Unnecessarily Complex Setup'], 0, 1, 'It unifies compute, network, storage, and virtualization.', 'UCS stands for Unified Computing System, Cisco''s integrated infrastructure platform that combines servers, networking, storage access, and virtualization into a single cohesive system.', true, 1),
('dc-003', 'DATA_CENTER', 'Which Nexus switch series is designed specifically for spine-leaf data center architectures?', ARRAY['Nexus 9000', 'Nexus 7000', 'Nexus 5000'], 0, 1, 'It''s the modern 9000 series built for fabrics.', 'The Nexus 9000 series is purpose-built for modern spine-leaf architectures, offering ultra-low latency, high bandwidth, and native ACI support for software-defined data centers.', true, 1),
('dc-004', 'DATA_CENTER', 'What is the name of Cisco''s centralized management platform for data center fabrics?', ARRAY['Nexus Dashboard', 'APIC', 'The Big Red Button'], 0, 1, 'It''s a dashboard for your Nexus environment.', 'Nexus Dashboard is Cisco''s unified operational console for managing ACI, VXLAN, and traditional data center fabrics, providing centralized visibility, automation, and troubleshooting.', true, 1),
('dc-005', 'DATA_CENTER', 'Which UCS server form factor is designed for high-density computing?', ARRAY['UCS Blade Servers', 'UCS Rack Servers', 'UCS Pizza Box Servers'], 0, 1, 'They slide into a chassis for maximum density.', 'UCS Blade Servers (B-Series) are designed for maximum density, sliding into UCS chassis with shared power, cooling, and fabric connectivity for space-efficient data centers.', true, 1),
('dc-006', 'DATA_CENTER', 'What network overlay technology does ACI use to create virtual networks?', ARRAY['VXLAN', 'OSPF', 'IS-IS'], 0, 1, 'It extends VLANs... virtually.', 'ACI uses VXLAN (Virtual Extensible LAN) as its network overlay technology, enabling scalable multi-tenancy and network segmentation across Layer 3 boundaries in the data center.', true, 1),
('dc-007', 'DATA_CENTER', 'What is the management controller embedded in UCS servers called?', ARRAY['CIMC', 'IMM', 'The Puppet Master'], 0, 1, 'It''s Cisco Integrated Management Controller.', 'CIMC (Cisco Integrated Management Controller) is the embedded management interface in UCS servers, providing out-of-band server management, monitoring, and remote console access.', true, 1),
('dc-008', 'DATA_CENTER', 'Which Nexus Dashboard service provides AI-powered network insights and recommendations?', ARRAY['Nexus Dashboard Insights', 'Nexus Dashboard Analytics', 'Magic 8-Ball as a Service'], 0, 1, 'It gives you insights into what''s happening.', 'Nexus Dashboard Insights uses AI and machine learning to provide proactive network visibility, anomaly detection, and actionable recommendations for ACI and VXLAN fabrics.', true, 1),
('dc-009', 'DATA_CENTER', 'What is the maximum number of leaf switches supported in a single ACI fabric?', ARRAY['400', '200', 'As many as you can afford'], 0, 1, 'It''s a round number between 200 and 500.', 'A single ACI fabric can scale to 400 leaf switches, supporting massive data center deployments with consistent policy enforcement and seamless multi-site connectivity.', true, 1),
('dc-010', 'DATA_CENTER', 'Which UCS component provides unified management across all UCS domains?', ARRAY['UCS Manager', 'UCS Central', 'Karen (she wants to speak to the manager)'], 0, 1, 'It manages your UCS environment.', 'UCS Manager is the unified management interface for UCS domains, providing service profiles, firmware management, and policy-based automation across compute, network, and storage resources.', true, 1),
('dc-011', 'DATA_CENTER', 'What technology allows ACI to extend policies across multiple data centers?', ARRAY['Multi-Site', 'Fabric Extend', 'Very Long Ethernet Cable'], 0, 1, 'It connects multiple sites together.', 'ACI Multi-Site enables policy consistency and workload mobility across geographically distributed data centers, with centralized orchestration through Multi-Site Orchestrator.', true, 1),
('dc-012', 'DATA_CENTER', 'Which Nexus switch includes embedded DPUs for advanced security processing?', ARRAY['Nexus 9300 Smart Switch', 'Nexus 9300 Dumb Switch', 'Nexus 9300 Genius Switch'], 0, 1, 'It''s smart because it has special processing units.', 'The Nexus 9300 Smart Switch includes embedded NVIDIA BlueField DPUs that provide line-rate security inspection, telemetry processing, and AI workload acceleration without impacting performance.', true, 1),
('dc-013', 'DATA_CENTER', 'What does APIC stand for in Cisco ACI?', ARRAY['Application Policy Infrastructure Controller', 'Automated Provisioning and Integration Controller', 'A Pretty Impressive Controller'], 0, 1, 'It controls the application policy infrastructure.', 'APIC is the centralized controller for ACI fabrics, translating application requirements into network policies and automating fabric configuration across all switches.', true, 1),
('dc-014', 'DATA_CENTER', 'Which UCS server generation introduced support for DDR5 memory?', ARRAY['UCS X-Series', 'UCS Y-Series', 'UCS Z-Series'], 0, 1, 'X marks the spot for the newest generation.', 'UCS X-Series is Cisco''s latest modular compute platform supporting DDR5 memory, PCIe Gen 5, and a future-ready design for AI, machine learning, and high-performance workloads.', true, 1),
('dc-015', 'DATA_CENTER', 'What fabric interconnect model is used in UCS blade chassis?', ARRAY['6400 Series', '5500 Series', '4400 Series'], 0, 1, 'It''s in the 6000 range and the latest generation.', 'The UCS 6400 Series Fabric Interconnects provide unified network and storage connectivity for UCS blade and rack servers with 10/25/40/100 Gigabit Ethernet ports.', true, 1),
('dc-016', 'DATA_CENTER', 'Which Nexus Dashboard service automates configuration compliance and auditing?', ARRAY['Nexus Dashboard Orchestrator', 'Nexus  Fabric Controller', 'Nexus Hall Monitor'], 0, 1, 'It orchestrates policies across your environment.', 'Nexus Dashboard Orchestrator provides centralized policy orchestration and compliance management across multiple ACI fabrics and cloud environments with automated auditing.', true, 1),
('dc-017', 'DATA_CENTER', 'What is the latency specification for Nexus 9000 series switches?', ARRAY['Sub-microsecond', 'Sub-millisecond', 'Sub-phemtosecond'], 0, 1, 'It''s measured in millionths of a second.', 'Nexus 9000 switches deliver sub-microsecond latency (less than 1 microsecond), critical for high-frequency trading, AI workloads, and latency-sensitive applications.', true, 1),
('dc-018', 'DATA_CENTER', 'Which ACI construct defines the logical grouping of endpoints?', ARRAY['Endpoint Group (EPG)', 'Bridge Domain', 'Endpoint Squad Goals'], 0, 1, 'It groups endpoints together logically.', 'Endpoint Groups (EPGs) are logical collections of endpoints in ACI that share common policy requirements, enabling simplified policy enforcement regardless of network topology.', true, 1),
('dc-019', 'DATA_CENTER', 'What GPU vendor does Cisco partner with for AI-optimized UCS servers?', ARRAY['NVIDIA', 'Intel', 'Nintendo'], 0, 1, 'The same company that makes GeForce graphics cards.', 'Cisco partners with NVIDIA to integrate GPU accelerators into UCS servers for AI training, inference, and high-performance computing workloads, validated for major AI frameworks.', true, 1),
('dc-020', 'DATA_CENTER', 'Which Nexus Dashboard service provides network security policy recommendations?', ARRAY['Nexus Dashboard Insights', 'Nexus Dashboard Security', 'Jeeves for Nexus Dashboard'], 0, 1, 'The same service that gives AI-powered insights.', 'Nexus Dashboard Insights analyzes traffic patterns and security postures to provide AI-driven recommendations for microsegmentation policies and security improvements in ACI environments.', true, 1);

-- ============================================================================
-- END OF TRIVIA MIGRATION
-- ============================================================================
-- Total Questions Inserted: 81
--   - NETWORKING: 25
--   - SECURITY: 18
--   - COLLABORATION: 18
--   - DATA_CENTER: 20
-- ============================================================================

-- Verify the migration
SELECT category, COUNT(*) as question_count
FROM trivia_items
GROUP BY category
ORDER BY category;
